//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YukiMcp.Yuki.Pettycash
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.theyukicompany.com/", ConfigurationName="YukiMcp.Yuki.Pettycash.PettyCashSoap")]
    public interface PettyCashSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/ImportStatement", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> ImportStatementAsync(string sessionID, string administrationID, string statementText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/ImportSingleStatementLine", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> ImportSingleStatementLineAsync(string sessionId, string accountGlCode, string transactionCode, string offsetAccount, string offsetName, System.DateTime transactionDate, string transactionDescription, decimal amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/ImportSingleStatementProjectLine", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> ImportSingleStatementProjectLineAsync(string sessionId, string accountGlCode, string transactionCode, string offsetAccount, string offsetName, System.DateTime transactionDate, string transactionDescription, decimal amount, string projectCode, string projectName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/Authenticate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> AuthenticateAsync(string accessKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/AuthenticateClient", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> AuthenticateClientAsync(string clientID, string clientSecret, string accessKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/AuthenticateByUserName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> AuthenticateByUserNameAsync(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/Domains", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> DomainsAsync(string sessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/Companies", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> CompaniesAsync(string sessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/AdministrationID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> AdministrationIDAsync(string sessionID, string administrationName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/Administrations", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> AdministrationsAsync(string sessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/AdministrationsWithInternalCustomerCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> AdministrationsWithInternalCustomerCodeAsync(string sessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/GetCurrentDomain", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetCurrentDomainAsync(string sessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/SetCurrentDomain", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task SetCurrentDomainAsync(string sessionID, string domainID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/Language", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> LanguageAsync(string sessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/SupportedLanguages", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> SupportedLanguagesAsync(string sessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/SetLanguage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task SetLanguageAsync(string sessionID, string language);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface PettyCashSoapChannel : YukiMcp.Yuki.Pettycash.PettyCashSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class PettyCashSoapClient : System.ServiceModel.ClientBase<YukiMcp.Yuki.Pettycash.PettyCashSoap>, YukiMcp.Yuki.Pettycash.PettyCashSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PettyCashSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(PettyCashSoapClient.GetBindingForEndpoint(endpointConfiguration), PettyCashSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PettyCashSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PettyCashSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PettyCashSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PettyCashSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PettyCashSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> ImportStatementAsync(string sessionID, string administrationID, string statementText)
        {
            return base.Channel.ImportStatementAsync(sessionID, administrationID, statementText);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> ImportSingleStatementLineAsync(string sessionId, string accountGlCode, string transactionCode, string offsetAccount, string offsetName, System.DateTime transactionDate, string transactionDescription, decimal amount)
        {
            return base.Channel.ImportSingleStatementLineAsync(sessionId, accountGlCode, transactionCode, offsetAccount, offsetName, transactionDate, transactionDescription, amount);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> ImportSingleStatementProjectLineAsync(string sessionId, string accountGlCode, string transactionCode, string offsetAccount, string offsetName, System.DateTime transactionDate, string transactionDescription, decimal amount, string projectCode, string projectName)
        {
            return base.Channel.ImportSingleStatementProjectLineAsync(sessionId, accountGlCode, transactionCode, offsetAccount, offsetName, transactionDate, transactionDescription, amount, projectCode, projectName);
        }
        
        public System.Threading.Tasks.Task<string> AuthenticateAsync(string accessKey)
        {
            return base.Channel.AuthenticateAsync(accessKey);
        }
        
        public System.Threading.Tasks.Task<string> AuthenticateClientAsync(string clientID, string clientSecret, string accessKey)
        {
            return base.Channel.AuthenticateClientAsync(clientID, clientSecret, accessKey);
        }
        
        public System.Threading.Tasks.Task<string> AuthenticateByUserNameAsync(string userName, string password)
        {
            return base.Channel.AuthenticateByUserNameAsync(userName, password);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> DomainsAsync(string sessionID)
        {
            return base.Channel.DomainsAsync(sessionID);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> CompaniesAsync(string sessionID)
        {
            return base.Channel.CompaniesAsync(sessionID);
        }
        
        public System.Threading.Tasks.Task<string> AdministrationIDAsync(string sessionID, string administrationName)
        {
            return base.Channel.AdministrationIDAsync(sessionID, administrationName);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> AdministrationsAsync(string sessionID)
        {
            return base.Channel.AdministrationsAsync(sessionID);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> AdministrationsWithInternalCustomerCodeAsync(string sessionID)
        {
            return base.Channel.AdministrationsWithInternalCustomerCodeAsync(sessionID);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetCurrentDomainAsync(string sessionID)
        {
            return base.Channel.GetCurrentDomainAsync(sessionID);
        }
        
        public System.Threading.Tasks.Task SetCurrentDomainAsync(string sessionID, string domainID)
        {
            return base.Channel.SetCurrentDomainAsync(sessionID, domainID);
        }
        
        public System.Threading.Tasks.Task<string> LanguageAsync(string sessionID)
        {
            return base.Channel.LanguageAsync(sessionID);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> SupportedLanguagesAsync(string sessionID)
        {
            return base.Channel.SupportedLanguagesAsync(sessionID);
        }
        
        public System.Threading.Tasks.Task SetLanguageAsync(string sessionID, string language)
        {
            return base.Channel.SetLanguageAsync(sessionID, language);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PettyCashSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.PettyCashSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PettyCashSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://api.yukiworks.be/ws/Pettycash.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.PettyCashSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://api.yukiworks.be/ws/Pettycash.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            PettyCashSoap,
            
            PettyCashSoap12,
        }
    }
}
