//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YukiMcp.Yuki.Projects
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.theyukicompany.com/", ConfigurationName="YukiMcp.Yuki.Projects.ProjectsSoap")]
    public interface ProjectsSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/UpdateProject", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task UpdateProjectAsync(string sessionID, string administrationID, YukiMcp.Yuki.Projects.Project project);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/Authenticate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> AuthenticateAsync(string accessKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/AuthenticateClient", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> AuthenticateClientAsync(string clientID, string clientSecret, string accessKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/AuthenticateByUserName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> AuthenticateByUserNameAsync(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/Domains", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> DomainsAsync(string sessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/Companies", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> CompaniesAsync(string sessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/AdministrationID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> AdministrationIDAsync(string sessionID, string administrationName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/Administrations", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> AdministrationsAsync(string sessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/AdministrationsWithInternalCustomerCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> AdministrationsWithInternalCustomerCodeAsync(string sessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/GetCurrentDomain", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetCurrentDomainAsync(string sessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/SetCurrentDomain", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task SetCurrentDomainAsync(string sessionID, string domainID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/Language", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> LanguageAsync(string sessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/SupportedLanguages", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> SupportedLanguagesAsync(string sessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/SetLanguage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task SetLanguageAsync(string sessionID, string language);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.theyukicompany.com/")]
    public partial class Project
    {
        
        private string descriptionField;
        
        private string codeField;
        
        private string companyField;
        
        private string managerField;
        
        private string contactField;
        
        private string notesField;
        
        private System.Nullable<short> securityLevelField;
        
        private System.Nullable<bool> allowOCRMatchingField;
        
        private System.Nullable<System.DateTime> startDateField;
        
        private System.Nullable<System.DateTime> endDateField;
        
        private System.Nullable<decimal> budgetRevenueField;
        
        private System.Nullable<decimal> budgetCostsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Company
        {
            get
            {
                return this.companyField;
            }
            set
            {
                this.companyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Manager
        {
            get
            {
                return this.managerField;
            }
            set
            {
                this.managerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Contact
        {
            get
            {
                return this.contactField;
            }
            set
            {
                this.contactField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Notes
        {
            get
            {
                return this.notesField;
            }
            set
            {
                this.notesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<short> SecurityLevel
        {
            get
            {
                return this.securityLevelField;
            }
            set
            {
                this.securityLevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<bool> AllowOCRMatching
        {
            get
            {
                return this.allowOCRMatchingField;
            }
            set
            {
                this.allowOCRMatchingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<System.DateTime> StartDate
        {
            get
            {
                return this.startDateField;
            }
            set
            {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<System.DateTime> EndDate
        {
            get
            {
                return this.endDateField;
            }
            set
            {
                this.endDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public System.Nullable<decimal> BudgetRevenue
        {
            get
            {
                return this.budgetRevenueField;
            }
            set
            {
                this.budgetRevenueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public System.Nullable<decimal> BudgetCosts
        {
            get
            {
                return this.budgetCostsField;
            }
            set
            {
                this.budgetCostsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface ProjectsSoapChannel : YukiMcp.Yuki.Projects.ProjectsSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class ProjectsSoapClient : System.ServiceModel.ClientBase<YukiMcp.Yuki.Projects.ProjectsSoap>, YukiMcp.Yuki.Projects.ProjectsSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ProjectsSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(ProjectsSoapClient.GetBindingForEndpoint(endpointConfiguration), ProjectsSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProjectsSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ProjectsSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProjectsSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ProjectsSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProjectsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task UpdateProjectAsync(string sessionID, string administrationID, YukiMcp.Yuki.Projects.Project project)
        {
            return base.Channel.UpdateProjectAsync(sessionID, administrationID, project);
        }
        
        public System.Threading.Tasks.Task<string> AuthenticateAsync(string accessKey)
        {
            return base.Channel.AuthenticateAsync(accessKey);
        }
        
        public System.Threading.Tasks.Task<string> AuthenticateClientAsync(string clientID, string clientSecret, string accessKey)
        {
            return base.Channel.AuthenticateClientAsync(clientID, clientSecret, accessKey);
        }
        
        public System.Threading.Tasks.Task<string> AuthenticateByUserNameAsync(string userName, string password)
        {
            return base.Channel.AuthenticateByUserNameAsync(userName, password);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> DomainsAsync(string sessionID)
        {
            return base.Channel.DomainsAsync(sessionID);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> CompaniesAsync(string sessionID)
        {
            return base.Channel.CompaniesAsync(sessionID);
        }
        
        public System.Threading.Tasks.Task<string> AdministrationIDAsync(string sessionID, string administrationName)
        {
            return base.Channel.AdministrationIDAsync(sessionID, administrationName);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> AdministrationsAsync(string sessionID)
        {
            return base.Channel.AdministrationsAsync(sessionID);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> AdministrationsWithInternalCustomerCodeAsync(string sessionID)
        {
            return base.Channel.AdministrationsWithInternalCustomerCodeAsync(sessionID);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetCurrentDomainAsync(string sessionID)
        {
            return base.Channel.GetCurrentDomainAsync(sessionID);
        }
        
        public System.Threading.Tasks.Task SetCurrentDomainAsync(string sessionID, string domainID)
        {
            return base.Channel.SetCurrentDomainAsync(sessionID, domainID);
        }
        
        public System.Threading.Tasks.Task<string> LanguageAsync(string sessionID)
        {
            return base.Channel.LanguageAsync(sessionID);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> SupportedLanguagesAsync(string sessionID)
        {
            return base.Channel.SupportedLanguagesAsync(sessionID);
        }
        
        public System.Threading.Tasks.Task SetLanguageAsync(string sessionID, string language)
        {
            return base.Channel.SetLanguageAsync(sessionID, language);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ProjectsSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.ProjectsSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ProjectsSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://api.yukiworks.be/ws/Projects.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.ProjectsSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://api.yukiworks.be/ws/Projects.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            ProjectsSoap,
            
            ProjectsSoap12,
        }
    }
}
