// <auto-generated>
// Generated from the live Yuki WSDL (see Yuki/AccountingInfo/AccountingInfoClient.cs) by
// scripts internal to this repo's setup - see plan.md, Fase 3. Hand-edit freely; this file is
// not regenerated automatically.
// </auto-generated>

using System.ComponentModel;
using ModelContextProtocol.Server;
using YukiMcp.Yuki;
using YukiMcp.Yuki.AccountingInfo;

namespace YukiMcp.Tools;

[McpServerToolType]
public static class AccountingInfoTools
{
    [McpServerTool(Name = "yuki_accounting_info_get_gl_account_scheme", ReadOnly = true, Destructive = false, Idempotent = true, OpenWorld = true)]
    [Description("Collects all ledger accounts (GL accounts) of the current domain.")]
    public static async System.Threading.Tasks.Task<string> GetGLAccountScheme(
        YukiSessionManager sessionManager,
        AccountingInfoSoapClient client,
        string administrationID)
    {
        var result = await sessionManager.ExecuteAsync(sessionId => client.GetGLAccountSchemeAsync(sessionId, administrationID));
        return YukiResult.Format(result);
    }

    [McpServerTool(Name = "yuki_accounting_info_get_custom_payment_methods", ReadOnly = true, Destructive = false, Idempotent = true, OpenWorld = true)]
    [Description("Collects all payment methods of the current domain.")]
    public static async System.Threading.Tasks.Task<string> GetCustomPaymentMethods(
        YukiSessionManager sessionManager,
        AccountingInfoSoapClient client,
        string administrationID)
    {
        var result = await sessionManager.ExecuteAsync(sessionId => client.GetCustomPaymentMethodsAsync(sessionId, administrationID));
        return YukiResult.Format(result);
    }

    [McpServerTool(Name = "yuki_accounting_info_get_rgs_scheme", ReadOnly = true, Destructive = false, Idempotent = true, OpenWorld = true)]
    [Description("Returns GLaccounts with corresponding RGS codes.")]
    public static async System.Threading.Tasks.Task<string> GetRGSScheme(
        YukiSessionManager sessionManager,
        AccountingInfoSoapClient client,
        string administrationID,
        string rgsVersion)
    {
        var result = await sessionManager.ExecuteAsync(sessionId => client.GetRGSSchemeAsync(sessionId, administrationID, rgsVersion));
        return YukiResult.Format(result);
    }

    [McpServerTool(Name = "yuki_accounting_info_get_period_date_table", ReadOnly = true, Destructive = false, Idempotent = true, OpenWorld = true)]
    [Description("Provides the start and end date of a fiscal year.")]
    public static async System.Threading.Tasks.Task<string> GetPeriodDateTable(
        YukiSessionManager sessionManager,
        AccountingInfoSoapClient client,
        string administrationID,
        int yearID)
    {
        var result = await sessionManager.ExecuteAsync(sessionId => client.GetPeriodDateTableAsync(sessionId, administrationID, yearID));
        return YukiResult.Format(result);
    }

    [McpServerTool(Name = "yuki_accounting_info_get_financial_year_modified_date", ReadOnly = true, Destructive = false, Idempotent = true, OpenWorld = true)]
    [Description("Calls the Yuki AccountingInfo.asmx \"GetFinancialYearModifiedDate\" operation (not documented in the public Yuki API reference; discovered via the live WSDL).")]
    public static async System.Threading.Tasks.Task<string> GetFinancialYearModifiedDate(
        YukiSessionManager sessionManager,
        AccountingInfoSoapClient client,
        string administrationID,
        int yearID)
    {
        var result = await sessionManager.ExecuteAsync(sessionId => client.GetFinancialYearModifiedDateAsync(sessionId, administrationID, yearID));
        return YukiResult.Format(result);
    }

    [McpServerTool(Name = "yuki_accounting_info_get_start_balance_by_gl_account", ReadOnly = true, Destructive = false, Idempotent = true, OpenWorld = true)]
    [Description("Provides the balance of all GL accounts.")]
    public static async System.Threading.Tasks.Task<string> GetStartBalanceByGlAccount(
        YukiSessionManager sessionManager,
        AccountingInfoSoapClient client,
        string administrationID,
        int bookyear,
        int financialMode)
    {
        var result = await sessionManager.ExecuteAsync(sessionId => client.GetStartBalanceByGlAccountAsync(sessionId, administrationID, bookyear, financialMode));
        return YukiResult.Format(result);
    }

    [McpServerTool(Name = "yuki_accounting_info_get_transaction_details", ReadOnly = true, Destructive = false, Idempotent = true, OpenWorld = true)]
    [Description("Provides transactions details of a GL accounts in the period between start date and end date.")]
    public static async System.Threading.Tasks.Task<string> GetTransactionDetails(
        YukiSessionManager sessionManager,
        AccountingInfoSoapClient client,
        string administrationID,
        string gLAccountCode,
        [Description("date/time, e.g. 2024-01-31")] System.DateTime startDate,
        [Description("date/time, e.g. 2024-01-31")] System.DateTime endDate,
        int financialMode)
    {
        var result = await sessionManager.ExecuteAsync(sessionId => client.GetTransactionDetailsAsync(sessionId, administrationID, gLAccountCode, startDate, endDate, financialMode));
        return YukiResult.Format(result);
    }

    [McpServerTool(Name = "yuki_accounting_info_get_transaction_document", ReadOnly = true, Destructive = false, Idempotent = true, OpenWorld = true)]
    [Description("Returns the document in a Base64 string for a specific document ID.")]
    public static async System.Threading.Tasks.Task<string> GetTransactionDocument(
        YukiSessionManager sessionManager,
        AccountingInfoSoapClient client,
        string administrationID,
        string transactionID)
    {
        var result = await sessionManager.ExecuteAsync(sessionId => client.GetTransactionDocumentAsync(sessionId, administrationID, transactionID));
        return YukiResult.Format(result);
    }

    [McpServerTool(Name = "yuki_accounting_info_get_contact_default_values", ReadOnly = true, Destructive = false, Idempotent = true, OpenWorld = true)]
    [Description("Calls the Yuki AccountingInfo.asmx \"GetContactDefaultValues\" operation (not documented in the public Yuki API reference; discovered via the live WSDL).")]
    public static async System.Threading.Tasks.Task<string> GetContactDefaultValues(
        YukiSessionManager sessionManager,
        AccountingInfoSoapClient client,
        string administrationID,
        string contactID)
    {
        var result = await sessionManager.ExecuteAsync(sessionId => client.GetContactDefaultValuesAsync(sessionId, administrationID, contactID));
        return YukiResult.Format(result);
    }

    [McpServerTool(Name = "yuki_accounting_info_get_transactions", ReadOnly = true, Destructive = false, Idempotent = true, OpenWorld = true)]
    [Description("Provides transactions details of a GL accounts in the period between start date and end date, along with extra related information provided from the requested dataGroups.")]
    public static async System.Threading.Tasks.Task<string> GetTransactions(
        YukiSessionManager sessionManager,
        AccountingInfoSoapClient client,
        string administrationID,
        string glAccountCode,
        [Description("date/time, e.g. 2024-01-31")] System.DateTime startDate,
        [Description("date/time, e.g. 2024-01-31")] System.DateTime endDate,
        int financialMode,
        string dataGroups,
        int numberOfRecords,
        int startRecord)
    {
        var result = await sessionManager.ExecuteAsync(sessionId => client.GetTransactionsAsync(sessionId, administrationID, glAccountCode, startDate, endDate, financialMode, dataGroups, numberOfRecords, startRecord, null));
        return YukiResult.Format(result.GetTransactionsResult);
    }

    [McpServerTool(Name = "yuki_accounting_info_get_project_balance", ReadOnly = true, Destructive = false, Idempotent = true, OpenWorld = true)]
    [Description("This call returns for each GLaccount the amount that is booked for a specific project.")]
    public static async System.Threading.Tasks.Task<string> GetProjectBalance(
        YukiSessionManager sessionManager,
        AccountingInfoSoapClient client,
        string administrationID,
        string gLAccountCode,
        string projectCode,
        [Description("date/time, e.g. 2024-01-31")] System.DateTime startDate,
        [Description("date/time, e.g. 2024-01-31")] System.DateTime endDate)
    {
        var result = await sessionManager.ExecuteAsync(sessionId => client.GetProjectBalanceAsync(sessionId, administrationID, gLAccountCode, projectCode, startDate, endDate));
        return YukiResult.Format(result);
    }

    [McpServerTool(Name = "yuki_accounting_info_get_projects", ReadOnly = true, Destructive = false, Idempotent = true, OpenWorld = true)]
    [Description("Returns the projects in for this administration.")]
    public static async System.Threading.Tasks.Task<string> GetProjects(
        YukiSessionManager sessionManager,
        AccountingInfoSoapClient client,
        string administrationID,
        [Description("one of: All, Company, Code, Description")] string searchOption,
        string searchValue)
    {
        var result = await sessionManager.ExecuteAsync(sessionId => client.GetProjectsAsync(sessionId, administrationID, YukiEnumHelper.Parse<YukiMcp.Yuki.AccountingInfo.ProjectSearchOption>(searchOption, nameof(searchOption)), searchValue));
        return YukiResult.Format(result);
    }

    [McpServerTool(Name = "yuki_accounting_info_get_projects_and_id", ReadOnly = true, Destructive = false, Idempotent = true, OpenWorld = true)]
    [Description("Returns the projects in for this administration with ID.")]
    public static async System.Threading.Tasks.Task<string> GetProjectsAndID(
        YukiSessionManager sessionManager,
        AccountingInfoSoapClient client,
        string administrationID,
        [Description("one of: All, Company, Code, Description")] string searchOption,
        string searchValue)
    {
        var result = await sessionManager.ExecuteAsync(sessionId => client.GetProjectsAndIDAsync(sessionId, administrationID, YukiEnumHelper.Parse<YukiMcp.Yuki.AccountingInfo.ProjectSearchOption>(searchOption, nameof(searchOption)), searchValue));
        return YukiResult.Format(result);
    }

}
