// <auto-generated>
// Generated from the live Yuki WSDL (see Yuki/Archive/ArchiveClient.cs) by
// scripts internal to this repo's setup - see plan.md, Fase 3. Hand-edit freely; this file is
// not regenerated automatically.
// </auto-generated>

using System.ComponentModel;
using ModelContextProtocol.Server;
using YukiMcp.Yuki;
using YukiMcp.Yuki.Archive;

namespace YukiMcp.Tools;

[McpServerToolType]
public static class ArchiveTools
{
    [McpServerTool(Name = "yuki_archive_document_folders", ReadOnly = true, Destructive = false, Idempotent = true, OpenWorld = true)]
    [Description("Provides all folders in the archive.")]
    public static async System.Threading.Tasks.Task<string> DocumentFolders(
        YukiSessionManager sessionManager,
        ArchiveSoapClient client)
    {
        var result = await sessionManager.ExecuteAsync(sessionId => client.DocumentFoldersAsync(sessionId));
        return YukiResult.Format(result);
    }

    [McpServerTool(Name = "yuki_archive_document_folder_counts", ReadOnly = true, Destructive = false, Idempotent = true, OpenWorld = true)]
    [Description("Provides the number of documents in each folder of the archive.")]
    public static async System.Threading.Tasks.Task<string> DocumentFolderCounts(
        YukiSessionManager sessionManager,
        ArchiveSoapClient client,
        int year)
    {
        var result = await sessionManager.ExecuteAsync(sessionId => client.DocumentFolderCountsAsync(sessionId, year));
        return YukiResult.Format(result);
    }

    [McpServerTool(Name = "yuki_archive_document_folder_tabs", ReadOnly = true, Destructive = false, Idempotent = true, OpenWorld = true)]
    [Description("Returns the tabs in a specific folder.")]
    public static async System.Threading.Tasks.Task<string> DocumentFolderTabs(
        YukiSessionManager sessionManager,
        ArchiveSoapClient client,
        string folderID)
    {
        var result = await sessionManager.ExecuteAsync(sessionId => client.DocumentFolderTabsAsync(sessionId, folderID));
        return YukiResult.Format(result);
    }

    [McpServerTool(Name = "yuki_archive_documents", ReadOnly = true, Destructive = false, Idempotent = true, OpenWorld = true)]
    [Description("Provides the documents in a folder with sorting options, date ranges and row number selection.")]
    public static async System.Threading.Tasks.Task<string> Documents(
        YukiSessionManager sessionManager,
        ArchiveSoapClient client,
        [Description("one of: CreatedDesc, CreatedAsc, ModifiedDesc, ModifiedAsc, DocumentDateDesc, DocumentDateAsc, ContactNameAsc, ContactNameDesc")] string sortOrder,
        [Description("date/time, e.g. 2024-01-31")] System.DateTime startDate,
        [Description("date/time, e.g. 2024-01-31")] System.DateTime endDate,
        int numberOfRecords,
        int startRecord)
    {
        var result = await sessionManager.ExecuteAsync(sessionId => client.DocumentsAsync(sessionId, YukiEnumHelper.Parse<YukiMcp.Yuki.Archive.DocumentSortOrder>(sortOrder, nameof(sortOrder)), startDate, endDate, numberOfRecords, startRecord));
        return YukiResult.Format(result);
    }

    [McpServerTool(Name = "yuki_archive_documents_in_folder", ReadOnly = true, Destructive = false, Idempotent = true, OpenWorld = true)]
    [Description("Provides the documents in a folder with sorting options, date ranges and row number selection.")]
    public static async System.Threading.Tasks.Task<string> DocumentsInFolder(
        YukiSessionManager sessionManager,
        ArchiveSoapClient client,
        int folderID,
        [Description("one of: CreatedDesc, CreatedAsc, ModifiedDesc, ModifiedAsc, DocumentDateDesc, DocumentDateAsc, ContactNameAsc, ContactNameDesc")] string sortOrder,
        [Description("date/time, e.g. 2024-01-31")] System.DateTime startDate,
        [Description("date/time, e.g. 2024-01-31")] System.DateTime endDate,
        int numberOfRecords,
        int startRecord)
    {
        var result = await sessionManager.ExecuteAsync(sessionId => client.DocumentsInFolderAsync(sessionId, folderID, YukiEnumHelper.Parse<YukiMcp.Yuki.Archive.DocumentSortOrder>(sortOrder, nameof(sortOrder)), startDate, endDate, numberOfRecords, startRecord));
        return YukiResult.Format(result);
    }

    [McpServerTool(Name = "yuki_archive_documents_in_tab", ReadOnly = true, Destructive = false, Idempotent = true, OpenWorld = true)]
    [Description("Provides the documents in a tab of a folder with sorting options, date ranges and row number selection.")]
    public static async System.Threading.Tasks.Task<string> DocumentsInTab(
        YukiSessionManager sessionManager,
        ArchiveSoapClient client,
        int tabID,
        [Description("one of: CreatedDesc, CreatedAsc, ModifiedDesc, ModifiedAsc, DocumentDateDesc, DocumentDateAsc, ContactNameAsc, ContactNameDesc")] string sortOrder,
        [Description("date/time, e.g. 2024-01-31")] System.DateTime startDate,
        [Description("date/time, e.g. 2024-01-31")] System.DateTime endDate,
        int numberOfRecords,
        int startRecord)
    {
        var result = await sessionManager.ExecuteAsync(sessionId => client.DocumentsInTabAsync(sessionId, tabID, YukiEnumHelper.Parse<YukiMcp.Yuki.Archive.DocumentSortOrder>(sortOrder, nameof(sortOrder)), startDate, endDate, numberOfRecords, startRecord));
        return YukiResult.Format(result);
    }

    [McpServerTool(Name = "yuki_archive_find_document", ReadOnly = true, Destructive = false, Idempotent = true, OpenWorld = true)]
    [Description("Returns the document information based on the DocumentID.")]
    public static async System.Threading.Tasks.Task<string> FindDocument(
        YukiSessionManager sessionManager,
        ArchiveSoapClient client,
        string documentID)
    {
        var result = await sessionManager.ExecuteAsync(sessionId => client.FindDocumentAsync(sessionId, documentID));
        return YukiResult.Format(result);
    }

    [McpServerTool(Name = "yuki_archive_documents_by_type", ReadOnly = true, Destructive = false, Idempotent = true, OpenWorld = true)]
    [Description("Returns document information for a specific document type in a specific period.")]
    public static async System.Threading.Tasks.Task<string> DocumentsByType(
        YukiSessionManager sessionManager,
        ArchiveSoapClient client,
        int documentType,
        [Description("one of: CreatedDesc, CreatedAsc, ModifiedDesc, ModifiedAsc, DocumentDateDesc, DocumentDateAsc, ContactNameAsc, ContactNameDesc")] string sortOrder,
        [Description("date/time, e.g. 2024-01-31")] System.DateTime startDate,
        [Description("date/time, e.g. 2024-01-31")] System.DateTime endDate,
        int numberOfRecords,
        int startRecord)
    {
        var result = await sessionManager.ExecuteAsync(sessionId => client.DocumentsByTypeAsync(sessionId, documentType, YukiEnumHelper.Parse<YukiMcp.Yuki.Archive.DocumentSortOrder>(sortOrder, nameof(sortOrder)), startDate, endDate, numberOfRecords, startRecord));
        return YukiResult.Format(result);
    }

    [McpServerTool(Name = "yuki_archive_modified_documents_by_type", ReadOnly = true, Destructive = false, Idempotent = true, OpenWorld = true)]
    [Description("Returns the documents that has been modified after a specific moment in time.")]
    public static async System.Threading.Tasks.Task<string> ModifiedDocumentsByType(
        YukiSessionManager sessionManager,
        ArchiveSoapClient client,
        int documentType,
        [Description("one of: CreatedDesc, CreatedAsc, ModifiedDesc, ModifiedAsc, DocumentDateDesc, DocumentDateAsc, ContactNameAsc, ContactNameDesc")] string sortOrder,
        [Description("date/time, e.g. 2024-01-31")] System.DateTime modifiedSince,
        int numberOfRecords,
        int startRecord)
    {
        var result = await sessionManager.ExecuteAsync(sessionId => client.ModifiedDocumentsByTypeAsync(sessionId, documentType, YukiEnumHelper.Parse<YukiMcp.Yuki.Archive.DocumentSortOrder>(sortOrder, nameof(sortOrder)), modifiedSince, numberOfRecords, startRecord));
        return YukiResult.Format(result);
    }

    [McpServerTool(Name = "yuki_archive_modified_documents_in_folder", ReadOnly = true, Destructive = false, Idempotent = true, OpenWorld = true)]
    [Description("Returns the documents that has been modified after a specific moment in time.")]
    public static async System.Threading.Tasks.Task<string> ModifiedDocumentsInFolder(
        YukiSessionManager sessionManager,
        ArchiveSoapClient client,
        int folderID,
        [Description("one of: CreatedDesc, CreatedAsc, ModifiedDesc, ModifiedAsc, DocumentDateDesc, DocumentDateAsc, ContactNameAsc, ContactNameDesc")] string sortOrder,
        [Description("date/time, e.g. 2024-01-31")] System.DateTime modifiedSince,
        int numberOfRecords,
        int startRecord)
    {
        var result = await sessionManager.ExecuteAsync(sessionId => client.ModifiedDocumentsInFolderAsync(sessionId, folderID, YukiEnumHelper.Parse<YukiMcp.Yuki.Archive.DocumentSortOrder>(sortOrder, nameof(sortOrder)), modifiedSince, numberOfRecords, startRecord));
        return YukiResult.Format(result);
    }

    [McpServerTool(Name = "yuki_archive_search_documents", ReadOnly = true, Destructive = false, Idempotent = true, OpenWorld = true)]
    [Description("Searches documents based on a search criteria. Use -1 for Folder or Tab or '0001-01-01' for date ranges, in case this should not be used.")]
    public static async System.Threading.Tasks.Task<string> SearchDocuments(
        YukiSessionManager sessionManager,
        ArchiveSoapClient client,
        [Description("one of: All, Creator, Contact, Subject, Tag, Type")] string searchOption,
        string searchText,
        int folderID,
        int tabID,
        [Description("one of: CreatedDesc, CreatedAsc, ModifiedDesc, ModifiedAsc, DocumentDateDesc, DocumentDateAsc, ContactNameAsc, ContactNameDesc")] string sortOrder,
        [Description("date/time, e.g. 2024-01-31")] System.DateTime startDate,
        [Description("date/time, e.g. 2024-01-31")] System.DateTime endDate,
        int numberOfRecords,
        int startRecord)
    {
        var result = await sessionManager.ExecuteAsync(sessionId => client.SearchDocumentsAsync(sessionId, YukiEnumHelper.Parse<YukiMcp.Yuki.Archive.SearchOption>(searchOption, nameof(searchOption)), searchText, folderID, tabID, YukiEnumHelper.Parse<YukiMcp.Yuki.Archive.DocumentSortOrder>(sortOrder, nameof(sortOrder)), startDate, endDate, numberOfRecords, startRecord));
        return YukiResult.Format(result);
    }

    [McpServerTool(Name = "yuki_archive_document_binary_data", ReadOnly = true, Destructive = false, Idempotent = true, OpenWorld = true)]
    [Description("Returns the document in Base64 string.")]
    public static async System.Threading.Tasks.Task<string> DocumentBinaryData(
        YukiSessionManager sessionManager,
        ArchiveSoapClient client,
        string documentID)
    {
        var result = await sessionManager.ExecuteAsync(sessionId => client.DocumentBinaryDataAsync(sessionId, documentID));
        return YukiResult.Format(result.DocumentBinaryDataResult);
    }

    [McpServerTool(Name = "yuki_archive_document_file", ReadOnly = true, Destructive = false, Idempotent = true, OpenWorld = true)]
    [Description("Returns the document in a Base64 string.")]
    public static async System.Threading.Tasks.Task<string> DocumentFile(
        YukiSessionManager sessionManager,
        ArchiveSoapClient client,
        string documentID)
    {
        var result = await sessionManager.ExecuteAsync(sessionId => client.DocumentFileAsync(sessionId, documentID));
        return YukiResult.Format(result);
    }

    [McpServerTool(Name = "yuki_archive_document_download_url", ReadOnly = true, Destructive = false, Idempotent = true, OpenWorld = true)]
    [Description("Calls the Yuki Archive.asmx \"DocumentDownloadUrl\" operation (not documented in the public Yuki API reference; discovered via the live WSDL).")]
    public static async System.Threading.Tasks.Task<string> DocumentDownloadUrl(
        YukiSessionManager sessionManager,
        ArchiveSoapClient client,
        string documentID)
    {
        var result = await sessionManager.ExecuteAsync(sessionId => client.DocumentDownloadUrlAsync(sessionId, documentID));
        return YukiResult.Format(result);
    }

    [McpServerTool(Name = "yuki_archive_document_xml_data", ReadOnly = true, Destructive = false, Idempotent = true, OpenWorld = true)]
    [Description("Retrieves the XML information of a document (only for invoices that has been delivered by the Sales webservice)")]
    public static async System.Threading.Tasks.Task<string> DocumentXMLData(
        YukiSessionManager sessionManager,
        ArchiveSoapClient client,
        string documentID)
    {
        var result = await sessionManager.ExecuteAsync(sessionId => client.DocumentXMLDataAsync(sessionId, documentID));
        return YukiResult.Format(result);
    }

    [McpServerTool(Name = "yuki_archive_document_xml_data_as_binary", ReadOnly = true, Destructive = false, Idempotent = true, OpenWorld = true)]
    [Description("Calls the Yuki Archive.asmx \"DocumentXMLDataAsBinary\" operation (not documented in the public Yuki API reference; discovered via the live WSDL).")]
    public static async System.Threading.Tasks.Task<string> DocumentXMLDataAsBinary(
        YukiSessionManager sessionManager,
        ArchiveSoapClient client,
        string documentID)
    {
        var result = await sessionManager.ExecuteAsync(sessionId => client.DocumentXMLDataAsBinaryAsync(sessionId, documentID));
        return YukiResult.Format(result.DocumentXMLDataAsBinaryResult);
    }

    [McpServerTool(Name = "yuki_archive_document_xml_data_as_string", ReadOnly = true, Destructive = false, Idempotent = true, OpenWorld = true)]
    [Description("Returns XML data in string format. (Only for invoices delivered by the Sales webservice)")]
    public static async System.Threading.Tasks.Task<string> DocumentXMLDataAsString(
        YukiSessionManager sessionManager,
        ArchiveSoapClient client,
        string documentID)
    {
        var result = await sessionManager.ExecuteAsync(sessionId => client.DocumentXMLDataAsStringAsync(sessionId, documentID));
        return YukiResult.Format(result);
    }

    [McpServerTool(Name = "yuki_archive_document_image", ReadOnly = true, Destructive = false, Idempotent = true, OpenWorld = true)]
    [Description("Provides the requested image of a document following the mentioned sizes as binary data.")]
    public static async System.Threading.Tasks.Task<string> DocumentImage(
        YukiSessionManager sessionManager,
        ArchiveSoapClient client,
        string documentID,
        int maxWidth,
        int maxHeight)
    {
        var result = await sessionManager.ExecuteAsync(sessionId => client.DocumentImageAsync(sessionId, documentID, maxWidth, maxHeight));
        return YukiResult.Format(result.DocumentImageResult);
    }

    [McpServerTool(Name = "yuki_archive_document_image_count", ReadOnly = true, Destructive = false, Idempotent = true, OpenWorld = true)]
    [Description("Provides the number of pages of a document.")]
    public static async System.Threading.Tasks.Task<string> DocumentImageCount(
        YukiSessionManager sessionManager,
        ArchiveSoapClient client,
        string documentID)
    {
        var result = await sessionManager.ExecuteAsync(sessionId => client.DocumentImageCountAsync(sessionId, documentID));
        return YukiResult.Format(result);
    }

    [McpServerTool(Name = "yuki_archive_document_bundle", ReadOnly = true, Destructive = false, Idempotent = true, OpenWorld = true)]
    [Description("Provides documents that are bundled with a main document.")]
    public static async System.Threading.Tasks.Task<string> DocumentBundle(
        YukiSessionManager sessionManager,
        ArchiveSoapClient client,
        string documentID)
    {
        var result = await sessionManager.ExecuteAsync(sessionId => client.DocumentBundleAsync(sessionId, documentID));
        return YukiResult.Format(result);
    }

    [McpServerTool(Name = "yuki_archive_upload_document", ReadOnly = false, Destructive = true, Idempotent = false, OpenWorld = true)]
    [Description("Calls the Yuki Archive.asmx \"UploadDocument\" operation (not documented in the public Yuki API reference; discovered via the live WSDL). This call creates or changes data in Yuki.")]
    public static async System.Threading.Tasks.Task<string> UploadDocument(
        YukiSessionManager sessionManager,
        ArchiveSoapClient client,
        string fileName,
        [Description("base64-encoded file content")] string data,
        int folder,
        string administrationID)
    {
        var result = await sessionManager.ExecuteAsync(sessionId => client.UploadDocumentAsync(sessionId, fileName, Convert.FromBase64String(data), folder, administrationID));
        return YukiResult.Format(result.UploadDocumentResult);
    }

    [McpServerTool(Name = "yuki_archive_upload_document_with_data", ReadOnly = false, Destructive = true, Idempotent = false, OpenWorld = true)]
    [Description("Calls the Yuki Archive.asmx \"UploadDocumentWithData\" operation (not documented in the public Yuki API reference; discovered via the live WSDL). This call creates or changes data in Yuki.")]
    public static async System.Threading.Tasks.Task<string> UploadDocumentWithData(
        YukiSessionManager sessionManager,
        ArchiveSoapClient client,
        string fileName,
        [Description("base64-encoded file content")] string data,
        int folder,
        string administrationID,
        string currency,
        decimal amount,
        string costCategory,
        int paymentMethod,
        string project,
        string remarks)
    {
        var result = await sessionManager.ExecuteAsync(sessionId => client.UploadDocumentWithDataAsync(sessionId, fileName, Convert.FromBase64String(data), folder, administrationID, currency, amount, costCategory, paymentMethod, project, remarks));
        return YukiResult.Format(result.UploadDocumentWithDataResult);
    }

    [McpServerTool(Name = "yuki_archive_upload_document_with_attachment", ReadOnly = false, Destructive = true, Idempotent = false, OpenWorld = true)]
    [Description("Calls the Yuki Archive.asmx \"UploadDocumentWithAttachment\" operation (not documented in the public Yuki API reference; discovered via the live WSDL). This call creates or changes data in Yuki.")]
    public static async System.Threading.Tasks.Task<string> UploadDocumentWithAttachment(
        YukiSessionManager sessionManager,
        ArchiveSoapClient client,
        string fileName1,
        [Description("base64-encoded file content")] string data1,
        string fileName2,
        [Description("base64-encoded file content")] string data2,
        int folder,
        string administrationID,
        string currency,
        decimal amount,
        string costCategory,
        int paymentMethod,
        string project,
        string remarks)
    {
        var result = await sessionManager.ExecuteAsync(sessionId => client.UploadDocumentWithAttachmentAsync(sessionId, fileName1, Convert.FromBase64String(data1), fileName2, Convert.FromBase64String(data2), folder, administrationID, currency, amount, costCategory, paymentMethod, project, remarks));
        return YukiResult.Format(result.UploadDocumentWithAttachmentResult);
    }

    [McpServerTool(Name = "yuki_archive_payment_methods", ReadOnly = true, Destructive = false, Idempotent = true, OpenWorld = true)]
    [Description("Provides the available payment methods that can be used for invoices. (do not use for sales webservice).")]
    public static async System.Threading.Tasks.Task<string> PaymentMethods(
        YukiSessionManager sessionManager,
        ArchiveSoapClient client)
    {
        var result = await sessionManager.ExecuteAsync(sessionId => client.PaymentMethodsAsync(sessionId));
        return YukiResult.Format(result);
    }

    [McpServerTool(Name = "yuki_archive_cost_categories", ReadOnly = true, Destructive = false, Idempotent = true, OpenWorld = true)]
    [Description("Provides a set of general enabled cost accounts.")]
    public static async System.Threading.Tasks.Task<string> CostCategories(
        YukiSessionManager sessionManager,
        ArchiveSoapClient client)
    {
        var result = await sessionManager.ExecuteAsync(sessionId => client.CostCategoriesAsync(sessionId));
        return YukiResult.Format(result);
    }

    [McpServerTool(Name = "yuki_archive_currencies", ReadOnly = true, Destructive = false, Idempotent = true, OpenWorld = true)]
    [Description("Returns the currencies available in the domain.")]
    public static async System.Threading.Tasks.Task<string> Currencies(
        YukiSessionManager sessionManager,
        ArchiveSoapClient client)
    {
        var result = await sessionManager.ExecuteAsync(sessionId => client.CurrenciesAsync(sessionId));
        return YukiResult.Format(result);
    }

    [McpServerTool(Name = "yuki_archive_menu", ReadOnly = true, Destructive = false, Idempotent = true, OpenWorld = true)]
    [Description("Displays the menu to use in apps.")]
    public static async System.Threading.Tasks.Task<string> Menu(
        YukiSessionManager sessionManager,
        ArchiveSoapClient client)
    {
        var result = await sessionManager.ExecuteAsync(sessionId => client.MenuAsync(sessionId));
        return YukiResult.Format(result);
    }

    [McpServerTool(Name = "yuki_archive_projects", ReadOnly = true, Destructive = false, Idempotent = true, OpenWorld = true)]
    [Description("Calls the Yuki Archive.asmx \"Projects\" operation (not documented in the public Yuki API reference; discovered via the live WSDL).")]
    public static async System.Threading.Tasks.Task<string> Projects(
        YukiSessionManager sessionManager,
        ArchiveSoapClient client,
        string administrationID)
    {
        var result = await sessionManager.ExecuteAsync(sessionId => client.ProjectsAsync(sessionId, administrationID));
        return YukiResult.Format(result);
    }

}
