// <auto-generated>
// Generated from the live Yuki WSDL (see Yuki/Backoffice/BackofficeClient.cs) by
// scripts internal to this repo's setup - see plan.md, Fase 3. Hand-edit freely; this file is
// not regenerated automatically.
// </auto-generated>

using System.ComponentModel;
using ModelContextProtocol.Server;
using YukiMcp.Yuki;
using YukiMcp.Yuki.Backoffice;

namespace YukiMcp.Tools;

[McpServerToolType]
public static class BackofficeTools
{
    [McpServerTool(Name = "yuki_backoffice_get_workflow", ReadOnly = true, Destructive = false, Idempotent = true, OpenWorld = true)]
    [Description("Calls the Yuki Backoffice.asmx \"GetWorkflow\" operation (not documented in the public Yuki API reference; discovered via the live WSDL).")]
    public static async System.Threading.Tasks.Task<string> GetWorkflow(
        YukiSessionManager sessionManager,
        BackofficeSoapClient client,
        string administrationID)
    {
        var result = await sessionManager.ExecuteAsync(sessionId => client.GetWorkflowAsync(sessionId, administrationID));
        return YukiResult.Format(result);
    }

    [McpServerTool(Name = "yuki_backoffice_get_outstanding_questions", ReadOnly = true, Destructive = false, Idempotent = true, OpenWorld = true)]
    [Description("Calls the Yuki Backoffice.asmx \"GetOutstandingQuestions\" operation (not documented in the public Yuki API reference; discovered via the live WSDL).")]
    public static async System.Threading.Tasks.Task<string> GetOutstandingQuestions(
        YukiSessionManager sessionManager,
        BackofficeSoapClient client,
        string administrationID)
    {
        var result = await sessionManager.ExecuteAsync(sessionId => client.GetOutstandingQuestionsAsync(sessionId, administrationID));
        return YukiResult.Format(result);
    }

}
