// <auto-generated>
// Generated from the live Yuki WSDL (see Yuki/ChangeDigest/ChangeDigestClient.cs) by
// scripts internal to this repo's setup - see plan.md, Fase 3. Hand-edit freely; this file is
// not regenerated automatically.
// </auto-generated>

using System.ComponentModel;
using ModelContextProtocol.Server;
using YukiMcp.Yuki;
using YukiMcp.Yuki.ChangeDigest;

namespace YukiMcp.Tools;

[McpServerToolType]
public static class ChangeDigestTools
{
    [McpServerTool(Name = "yuki_change_digest_get_updated_and_deleted_transactions", ReadOnly = true, Destructive = false, Idempotent = true, OpenWorld = true)]
    [Description("Calls the Yuki ChangeDigest.asmx \"GetUpdatedAndDeletedTransactions\" operation (not documented in the public Yuki API reference; discovered via the live WSDL).")]
    public static async System.Threading.Tasks.Task<string> GetUpdatedAndDeletedTransactions(
        YukiSessionManager sessionManager,
        ChangeDigestSoapClient client,
        string administrationID,
        [Description("date/time, e.g. 2024-01-31")] System.DateTime startDate,
        [Description("date/time, e.g. 2024-01-31")] System.DateTime endDate,
        int numberOfRecords,
        int startRecord)
    {
        var result = await sessionManager.ExecuteAsync(sessionId => client.GetUpdatedAndDeletedTransactionsAsync(sessionId, administrationID, startDate, endDate, numberOfRecords, startRecord));
        return YukiResult.Format(result.GetUpdatedAndDeletedTransactionsResult);
    }

    [McpServerTool(Name = "yuki_change_digest_get_transaction_detail", ReadOnly = true, Destructive = false, Idempotent = true, OpenWorld = true)]
    [Description("Calls the Yuki ChangeDigest.asmx \"GetTransactionDetail\" operation (not documented in the public Yuki API reference; discovered via the live WSDL).")]
    public static async System.Threading.Tasks.Task<string> GetTransactionDetail(
        YukiSessionManager sessionManager,
        ChangeDigestSoapClient client,
        string administrationID,
        string transactionID)
    {
        var result = await sessionManager.ExecuteAsync(sessionId => client.GetTransactionDetailAsync(sessionId, administrationID, transactionID));
        return YukiResult.Format(result);
    }

}
