// <auto-generated>
// Generated from the live Yuki WSDL (see Yuki/Domains/DomainsClient.cs) by
// scripts internal to this repo's setup - see plan.md, Fase 3. Hand-edit freely; this file is
// not regenerated automatically.
// </auto-generated>

using System.ComponentModel;
using ModelContextProtocol.Server;
using YukiMcp.Yuki;
using YukiMcp.Yuki.Domains;

namespace YukiMcp.Tools;

[McpServerToolType]
public static class DomainsTools
{
    [McpServerTool(Name = "yuki_domains_get_domain_name", ReadOnly = true, Destructive = false, Idempotent = true, OpenWorld = true)]
    [Description("Calls the Yuki Domains.asmx \"GetDomainName\" operation (not documented in the public Yuki API reference; discovered via the live WSDL).")]
    public static async System.Threading.Tasks.Task<string> GetDomainName(
        YukiSessionManager sessionManager,
        DomainsSoapClient client,
        string administrationName)
    {
        var result = await sessionManager.ExecuteAsync(sessionId => client.GetDomainNameAsync(sessionId, administrationName));
        return YukiResult.Format(result);
    }

    [McpServerTool(Name = "yuki_domains_create_domain", ReadOnly = false, Destructive = true, Idempotent = false, OpenWorld = true)]
    [Description("Calls the Yuki Domains.asmx \"CreateDomain\" operation (not documented in the public Yuki API reference; discovered via the live WSDL). This call creates or changes data in Yuki.")]
    public static async System.Threading.Tasks.Task<string> CreateDomain(
        YukiSessionManager sessionManager,
        DomainsSoapClient client,
        string administrationName,
        string domainName,
        string defaultLanguage)
    {
        var result = await sessionManager.ExecuteAsync(sessionId => client.CreateDomainAsync(sessionId, administrationName, domainName, defaultLanguage));
        return YukiResult.Format(result);
    }

    [McpServerTool(Name = "yuki_domains_create_trial_domain", ReadOnly = false, Destructive = true, Idempotent = false, OpenWorld = true)]
    [Description("Calls the Yuki Domains.asmx \"CreateTrialDomain\" operation (not documented in the public Yuki API reference; discovered via the live WSDL). This call creates or changes data in Yuki.")]
    public static async System.Threading.Tasks.Task<string> CreateTrialDomain(
        YukiSessionManager sessionManager,
        DomainsSoapClient client,
        string administrationName,
        string domainName,
        string defaultLanguage)
    {
        var result = await sessionManager.ExecuteAsync(sessionId => client.CreateTrialDomainAsync(sessionId, administrationName, domainName, defaultLanguage));
        return YukiResult.Format(result);
    }

    [McpServerTool(Name = "yuki_domains_get_domain_users", ReadOnly = true, Destructive = false, Idempotent = true, OpenWorld = true)]
    [Description("Calls the Yuki Domains.asmx \"GetDomainUsers\" operation (not documented in the public Yuki API reference; discovered via the live WSDL).")]
    public static async System.Threading.Tasks.Task<string> GetDomainUsers(
        YukiSessionManager sessionManager,
        DomainsSoapClient client,
        string domain)
    {
        var result = await sessionManager.ExecuteAsync(sessionId => client.GetDomainUsersAsync(sessionId, domain));
        return YukiResult.Format(result);
    }

    [McpServerTool(Name = "yuki_domains_add_domain_user", ReadOnly = false, Destructive = true, Idempotent = false, OpenWorld = true)]
    [Description("Calls the Yuki Domains.asmx \"AddDomainUser\" operation (not documented in the public Yuki API reference; discovered via the live WSDL). This call creates or changes data in Yuki.")]
    public static async System.Threading.Tasks.Task<string> AddDomainUser(
        YukiSessionManager sessionManager,
        DomainsSoapClient client,
        string domain,
        string email,
        string name,
        string roles,
        string administrations,
        bool sendMessage,
        string customMessage,
        string language)
    {
        var result = await sessionManager.ExecuteAsync(sessionId => client.AddDomainUserAsync(sessionId, domain, email, name, roles, administrations, sendMessage, customMessage, language));
        return YukiResult.Format(result);
    }

    [McpServerTool(Name = "yuki_domains_get_domain_functions", ReadOnly = true, Destructive = false, Idempotent = true, OpenWorld = true)]
    [Description("Calls the Yuki Domains.asmx \"GetDomainFunctions\" operation (not documented in the public Yuki API reference; discovered via the live WSDL).")]
    public static async System.Threading.Tasks.Task<string> GetDomainFunctions(
        YukiSessionManager sessionManager,
        DomainsSoapClient client,
        string domain)
    {
        var result = await sessionManager.ExecuteAsync(sessionId => client.GetDomainFunctionsAsync(sessionId, domain));
        return YukiResult.Format(result);
    }

    [McpServerTool(Name = "yuki_domains_update_domain_functions", ReadOnly = false, Destructive = true, Idempotent = false, OpenWorld = true)]
    [Description("Calls the Yuki Domains.asmx \"UpdateDomainFunctions\" operation (not documented in the public Yuki API reference; discovered via the live WSDL). This call creates or changes data in Yuki.")]
    public static async System.Threading.Tasks.Task<string> UpdateDomainFunctions(
        YukiSessionManager sessionManager,
        DomainsSoapClient client,
        string domain,
        [Description("one of: BOResponsible, BOBackup, BOController, BOAccountManager")] string domainFunction,
        string login)
    {
        var result = await sessionManager.ExecuteAsync(sessionId => client.UpdateDomainFunctionsAsync(sessionId, domain, YukiEnumHelper.Parse<YukiMcp.Yuki.Domains.DomainFunction>(domainFunction, nameof(domainFunction)), login));
        return YukiResult.Format(result);
    }

    [McpServerTool(Name = "yuki_domains_lyanthe_recognition_engine", ReadOnly = false, Destructive = true, Idempotent = false, OpenWorld = true)]
    [Description("Calls the Yuki Domains.asmx \"LyantheRecognitionEngine\" operation (not documented in the public Yuki API reference; discovered via the live WSDL). This call creates or changes data in Yuki.")]
    public static async System.Threading.Tasks.Task<string> LyantheRecognitionEngine(
        YukiSessionManager sessionManager,
        DomainsSoapClient client,
        string domain,
        bool enableLyanthe)
    {
        var result = await sessionManager.ExecuteAsync(sessionId => client.LyantheRecognitionEngineAsync(sessionId, domain, enableLyanthe));
        return YukiResult.Format(result);
    }

}
