// <auto-generated>
// Generated from the live Yuki WSDL (see Yuki/FiscalTable/FiscalTableClient.cs) by
// scripts internal to this repo's setup - see plan.md, Fase 3. Hand-edit freely; this file is
// not regenerated automatically.
// </auto-generated>

using System.ComponentModel;
using ModelContextProtocol.Server;
using YukiMcp.Yuki;
using YukiMcp.Yuki.FiscalTable;

namespace YukiMcp.Tools;

[McpServerToolType]
public static class FiscalTableTools
{
    [McpServerTool(Name = "yuki_fiscal_table_get_fiscal_table", ReadOnly = true, Destructive = false, Idempotent = true, OpenWorld = true)]
    [Description("This call allows you to retrieve the gross amount, total professional costs, total social contributions and total revenue in a specific year of a company")]
    public static async System.Threading.Tasks.Task<string> GetFiscalTable(
        YukiSessionManager sessionManager,
        FiscalTableSoapClient client,
        string companyId,
        int year)
    {
        var result = await sessionManager.ExecuteAsync(sessionId => client.GetFiscalTableAsync(sessionId, companyId, year));
        return YukiResult.Format(result);
    }

}
