// <auto-generated>
// Hand-curated wrapper for the handful of Yuki operations that exist identically on
// every .asmx service (see plan.md, "Sessie- en authenticatiebeheer" / Fase 3). They are
// only exposed once here, bound to the Sales client, instead of once per service.
// </auto-generated>

using System.ComponentModel;
using ModelContextProtocol.Server;
using YukiMcp.Yuki;
using YukiMcp.Yuki.Sales;

namespace YukiMcp.Tools;

[McpServerToolType]
public static class GeneralTools
{
    [McpServerTool(Name = "yuki_general_domains", ReadOnly = true, Destructive = false, Idempotent = true, OpenWorld = true)]
    [Description("Provides all domains that can be accessed through the used access code.")]
    public static async System.Threading.Tasks.Task<string> Domains(
        YukiSessionManager sessionManager,
        SalesSoapClient client)
    {
        var result = await sessionManager.ExecuteAsync(sessionId => client.DomainsAsync(sessionId));
        return YukiResult.Format(result);
    }

    [McpServerTool(Name = "yuki_general_companies", ReadOnly = true, Destructive = false, Idempotent = true, OpenWorld = true)]
    [Description("Returns the administrations this session ID has access to")]
    public static async System.Threading.Tasks.Task<string> Companies(
        YukiSessionManager sessionManager,
        SalesSoapClient client)
    {
        var result = await sessionManager.ExecuteAsync(sessionId => client.CompaniesAsync(sessionId));
        return YukiResult.Format(result);
    }

    [McpServerTool(Name = "yuki_general_administration_id", ReadOnly = true, Destructive = false, Idempotent = true, OpenWorld = true)]
    [Description("Use the username (emailadress) and password of the user to create a session ID. The session ID is valid for 24h or until closing the application. Use the session ID to make the connection to Yuki in the following calls.")]
    public static async System.Threading.Tasks.Task<string> AdministrationID(
        YukiSessionManager sessionManager,
        SalesSoapClient client,
        string administrationName)
    {
        var result = await sessionManager.ExecuteAsync(sessionId => client.AdministrationIDAsync(sessionId, administrationName));
        return YukiResult.Format(result);
    }

    [McpServerTool(Name = "yuki_general_administrations", ReadOnly = true, Destructive = false, Idempotent = true, OpenWorld = true)]
    [Description("Returns the company details of the administration")]
    public static async System.Threading.Tasks.Task<string> Administrations(
        YukiSessionManager sessionManager,
        SalesSoapClient client)
    {
        var result = await sessionManager.ExecuteAsync(sessionId => client.AdministrationsAsync(sessionId));
        return YukiResult.Format(result);
    }

    [McpServerTool(Name = "yuki_general_administrations_with_internal_customer_code", ReadOnly = true, Destructive = false, Idempotent = true, OpenWorld = true)]
    [Description("Calls the Yuki Sales.asmx \"AdministrationsWithInternalCustomerCode\" operation (not documented in the public Yuki API reference; discovered via the live WSDL).")]
    public static async System.Threading.Tasks.Task<string> AdministrationsWithInternalCustomerCode(
        YukiSessionManager sessionManager,
        SalesSoapClient client)
    {
        var result = await sessionManager.ExecuteAsync(sessionId => client.AdministrationsWithInternalCustomerCodeAsync(sessionId));
        return YukiResult.Format(result);
    }

    [McpServerTool(Name = "yuki_general_get_current_domain", ReadOnly = true, Destructive = false, Idempotent = true, OpenWorld = true)]
    [Description("Returns the current domain for which the session is active")]
    public static async System.Threading.Tasks.Task<string> GetCurrentDomain(
        YukiSessionManager sessionManager,
        SalesSoapClient client)
    {
        var result = await sessionManager.ExecuteAsync(sessionId => client.GetCurrentDomainAsync(sessionId));
        return YukiResult.Format(result);
    }

    [McpServerTool(Name = "yuki_general_language", ReadOnly = true, Destructive = false, Idempotent = true, OpenWorld = true)]
    [Description("Returns the language of the administration")]
    public static async System.Threading.Tasks.Task<string> Language(
        YukiSessionManager sessionManager,
        SalesSoapClient client)
    {
        var result = await sessionManager.ExecuteAsync(sessionId => client.LanguageAsync(sessionId));
        return YukiResult.Format(result);
    }

    [McpServerTool(Name = "yuki_general_supported_languages", ReadOnly = true, Destructive = false, Idempotent = true, OpenWorld = true)]
    [Description("Returns the language available in this domain")]
    public static async System.Threading.Tasks.Task<string> SupportedLanguages(
        YukiSessionManager sessionManager,
        SalesSoapClient client)
    {
        var result = await sessionManager.ExecuteAsync(sessionId => client.SupportedLanguagesAsync(sessionId));
        return YukiResult.Format(result);
    }

}
