// <auto-generated>
// Generated from the live Yuki WSDL (see Yuki/Integration/IntegrationClient.cs) by
// scripts internal to this repo's setup - see plan.md, Fase 3. Hand-edit freely; this file is
// not regenerated automatically.
// </auto-generated>

using System.ComponentModel;
using ModelContextProtocol.Server;
using YukiMcp.Yuki;
using YukiMcp.Yuki.Integration;

namespace YukiMcp.Tools;

[McpServerToolType]
public static class IntegrationTools
{
    [McpServerTool(Name = "yuki_integration_get_administration_data", ReadOnly = true, Destructive = false, Idempotent = true, OpenWorld = true)]
    [Description("Calls the Yuki Integration.asmx \"GetAdministrationData\" operation (not documented in the public Yuki API reference; discovered via the live WSDL).")]
    public static async System.Threading.Tasks.Task<string> GetAdministrationData(
        YukiSessionManager sessionManager,
        IntegrationSoapClient client,
        string administrationId)
    {
        var result = await sessionManager.ExecuteAsync(sessionId => client.GetAdministrationDataAsync(sessionId, administrationId));
        return YukiResult.Format(result);
    }

}
