// <auto-generated>
// Generated from the live Yuki WSDL (see Yuki/Vat/VatClient.cs) by
// scripts internal to this repo's setup - see plan.md, Fase 3. Hand-edit freely; this file is
// not regenerated automatically.
// </auto-generated>

using System.ComponentModel;
using ModelContextProtocol.Server;
using YukiMcp.Yuki;
using YukiMcp.Yuki.Vat;

namespace YukiMcp.Tools;

[McpServerToolType]
public static class VatTools
{
    [McpServerTool(Name = "yuki_vat_vat_return_list", ReadOnly = true, Destructive = false, Idempotent = true, OpenWorld = true)]
    [Description("Returns the status and additional information on the VAT returns of an administration.")]
    public static async System.Threading.Tasks.Task<string> VATReturnList(
        YukiSessionManager sessionManager,
        VATSoapClient client,
        string administrationID,
        int year,
        [Description("date/time, e.g. 2024-01-31")] System.DateTime modifiedAfter)
    {
        var result = await sessionManager.ExecuteAsync(sessionId => client.VATReturnListAsync(sessionId, administrationID, year, modifiedAfter));
        return YukiResult.Format(result);
    }

    [McpServerTool(Name = "yuki_vat_active_vat_codes_list", ReadOnly = true, Destructive = false, Idempotent = true, OpenWorld = true)]
    [Description("Returns the active vat codes of an administration.")]
    public static async System.Threading.Tasks.Task<string> ActiveVATCodesList(
        YukiSessionManager sessionManager,
        VATSoapClient client,
        string administrationID)
    {
        var result = await sessionManager.ExecuteAsync(sessionId => client.ActiveVATCodesListAsync(sessionId, administrationID));
        return YukiResult.Format(result);
    }

}
