//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YukiMcp.Yuki.Vat
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.theyukicompany.com/", ConfigurationName="YukiMcp.Yuki.Vat.VATSoap")]
    public interface VATSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/VATReturnList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<YukiMcp.Yuki.Vat.VATReturnInfo[]> VATReturnListAsync(string sessionID, string administrationID, int year, System.DateTime modifiedAfter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/ActiveVATCodesList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<YukiMcp.Yuki.Vat.VATCode[]> ActiveVATCodesListAsync(string sessionID, string administrationID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/Authenticate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> AuthenticateAsync(string accessKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/AuthenticateClient", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> AuthenticateClientAsync(string clientID, string clientSecret, string accessKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/AuthenticateByUserName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> AuthenticateByUserNameAsync(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/Domains", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> DomainsAsync(string sessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/Companies", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> CompaniesAsync(string sessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/AdministrationID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> AdministrationIDAsync(string sessionID, string administrationName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/Administrations", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> AdministrationsAsync(string sessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/AdministrationsWithInternalCustomerCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> AdministrationsWithInternalCustomerCodeAsync(string sessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/GetCurrentDomain", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetCurrentDomainAsync(string sessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/SetCurrentDomain", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task SetCurrentDomainAsync(string sessionID, string domainID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/Language", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> LanguageAsync(string sessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/SupportedLanguages", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> SupportedLanguagesAsync(string sessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/SetLanguage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task SetLanguageAsync(string sessionID, string language);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.theyukicompany.com/")]
    public partial class VATReturnInfo
    {
        
        private string documentIDField;
        
        private System.DateTime startDateField;
        
        private System.DateTime endDateField;
        
        private string statusField;
        
        private System.Nullable<System.DateTime> sendDateField;
        
        private System.Nullable<System.DateTime> acknowledgeDateField;
        
        private System.DateTime modifiedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string documentID
        {
            get
            {
                return this.documentIDField;
            }
            set
            {
                this.documentIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime startDate
        {
            get
            {
                return this.startDateField;
            }
            set
            {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime endDate
        {
            get
            {
                return this.endDateField;
            }
            set
            {
                this.endDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<System.DateTime> sendDate
        {
            get
            {
                return this.sendDateField;
            }
            set
            {
                this.sendDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<System.DateTime> acknowledgeDate
        {
            get
            {
                return this.acknowledgeDateField;
            }
            set
            {
                this.acknowledgeDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public System.DateTime modified
        {
            get
            {
                return this.modifiedField;
            }
            set
            {
                this.modifiedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.theyukicompany.com/")]
    public partial class VATCode
    {
        
        private string descriptionField;
        
        private int typeField;
        
        private string typeDescriptionField;
        
        private decimal percentageField;
        
        private string countryField;
        
        private System.Nullable<System.DateTime> startDateField;
        
        private System.Nullable<System.DateTime> endDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string typeDescription
        {
            get
            {
                return this.typeDescriptionField;
            }
            set
            {
                this.typeDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal percentage
        {
            get
            {
                return this.percentageField;
            }
            set
            {
                this.percentageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<System.DateTime> startDate
        {
            get
            {
                return this.startDateField;
            }
            set
            {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<System.DateTime> endDate
        {
            get
            {
                return this.endDateField;
            }
            set
            {
                this.endDateField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface VATSoapChannel : YukiMcp.Yuki.Vat.VATSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class VATSoapClient : System.ServiceModel.ClientBase<YukiMcp.Yuki.Vat.VATSoap>, YukiMcp.Yuki.Vat.VATSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public VATSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(VATSoapClient.GetBindingForEndpoint(endpointConfiguration), VATSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public VATSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(VATSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public VATSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(VATSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public VATSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<YukiMcp.Yuki.Vat.VATReturnInfo[]> VATReturnListAsync(string sessionID, string administrationID, int year, System.DateTime modifiedAfter)
        {
            return base.Channel.VATReturnListAsync(sessionID, administrationID, year, modifiedAfter);
        }
        
        public System.Threading.Tasks.Task<YukiMcp.Yuki.Vat.VATCode[]> ActiveVATCodesListAsync(string sessionID, string administrationID)
        {
            return base.Channel.ActiveVATCodesListAsync(sessionID, administrationID);
        }
        
        public System.Threading.Tasks.Task<string> AuthenticateAsync(string accessKey)
        {
            return base.Channel.AuthenticateAsync(accessKey);
        }
        
        public System.Threading.Tasks.Task<string> AuthenticateClientAsync(string clientID, string clientSecret, string accessKey)
        {
            return base.Channel.AuthenticateClientAsync(clientID, clientSecret, accessKey);
        }
        
        public System.Threading.Tasks.Task<string> AuthenticateByUserNameAsync(string userName, string password)
        {
            return base.Channel.AuthenticateByUserNameAsync(userName, password);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> DomainsAsync(string sessionID)
        {
            return base.Channel.DomainsAsync(sessionID);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> CompaniesAsync(string sessionID)
        {
            return base.Channel.CompaniesAsync(sessionID);
        }
        
        public System.Threading.Tasks.Task<string> AdministrationIDAsync(string sessionID, string administrationName)
        {
            return base.Channel.AdministrationIDAsync(sessionID, administrationName);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> AdministrationsAsync(string sessionID)
        {
            return base.Channel.AdministrationsAsync(sessionID);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> AdministrationsWithInternalCustomerCodeAsync(string sessionID)
        {
            return base.Channel.AdministrationsWithInternalCustomerCodeAsync(sessionID);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetCurrentDomainAsync(string sessionID)
        {
            return base.Channel.GetCurrentDomainAsync(sessionID);
        }
        
        public System.Threading.Tasks.Task SetCurrentDomainAsync(string sessionID, string domainID)
        {
            return base.Channel.SetCurrentDomainAsync(sessionID, domainID);
        }
        
        public System.Threading.Tasks.Task<string> LanguageAsync(string sessionID)
        {
            return base.Channel.LanguageAsync(sessionID);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> SupportedLanguagesAsync(string sessionID)
        {
            return base.Channel.SupportedLanguagesAsync(sessionID);
        }
        
        public System.Threading.Tasks.Task SetLanguageAsync(string sessionID, string language)
        {
            return base.Channel.SetLanguageAsync(sessionID, language);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.VATSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.VATSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.VATSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://api.yukiworks.be/ws/Vat.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.VATSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://api.yukiworks.be/ws/Vat.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            VATSoap,
            
            VATSoap12,
        }
    }
}
