//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YukiMcp.Yuki.Contact
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.theyukicompany.com/", ConfigurationName="YukiMcp.Yuki.Contact.ContactSoap")]
    public interface ContactSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/SearchContacts", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<YukiMcp.Yuki.Contact.SearchContactsResponse> SearchContactsAsync(YukiMcp.Yuki.Contact.SearchContactsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/GetSuppliersAndCustomers", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<YukiMcp.Yuki.Contact.GetSuppliersAndCustomersResponse> GetSuppliersAndCustomersAsync(YukiMcp.Yuki.Contact.GetSuppliersAndCustomersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/UpdateContact", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> UpdateContactAsync(string sessionID, string domainID, System.Xml.XmlNode xmlDoc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/Authenticate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> AuthenticateAsync(string accessKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/AuthenticateClient", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> AuthenticateClientAsync(string clientID, string clientSecret, string accessKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/AuthenticateByUserName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> AuthenticateByUserNameAsync(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/Domains", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> DomainsAsync(string sessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/Companies", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> CompaniesAsync(string sessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/AdministrationID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> AdministrationIDAsync(string sessionID, string administrationName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/Administrations", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> AdministrationsAsync(string sessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/AdministrationsWithInternalCustomerCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> AdministrationsWithInternalCustomerCodeAsync(string sessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/GetCurrentDomain", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetCurrentDomainAsync(string sessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/SetCurrentDomain", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task SetCurrentDomainAsync(string sessionID, string domainID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/Language", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> LanguageAsync(string sessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/SupportedLanguages", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> SupportedLanguagesAsync(string sessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/SetLanguage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task SetLanguageAsync(string sessionID, string language);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.theyukicompany.com/")]
    public enum ContactSearchOption
    {
        
        /// <remarks/>
        All,
        
        /// <remarks/>
        Name,
        
        /// <remarks/>
        City,
        
        /// <remarks/>
        Postcode,
        
        /// <remarks/>
        Tag,
        
        /// <remarks/>
        Email,
        
        /// <remarks/>
        Website,
        
        /// <remarks/>
        Phone,
        
        /// <remarks/>
        Code,
        
        /// <remarks/>
        CoCNumber,
        
        /// <remarks/>
        VATNumber,
        
        /// <remarks/>
        BankAccount,
        
        /// <remarks/>
        ID,
        
        /// <remarks/>
        ContactType,
        
        /// <remarks/>
        HID,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.theyukicompany.com/")]
    public enum ContactSortOrder
    {
        
        /// <remarks/>
        Name,
        
        /// <remarks/>
        LastName,
        
        /// <remarks/>
        CreatedAsc,
        
        /// <remarks/>
        CreatedDesc,
        
        /// <remarks/>
        ModifiedAsc,
        
        /// <remarks/>
        ModifiedDesc,
        
        /// <remarks/>
        HID,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.theyukicompany.com/")]
    public enum ContactActive
    {
        
        /// <remarks/>
        Both,
        
        /// <remarks/>
        Active,
        
        /// <remarks/>
        Inactive,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchContacts", WrapperNamespace="http://www.theyukicompany.com/", IsWrapped=true)]
    public partial class SearchContactsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.theyukicompany.com/", Order=0)]
        public string sessionID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.theyukicompany.com/", Order=1)]
        public string domainID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.theyukicompany.com/", Order=2)]
        public YukiMcp.Yuki.Contact.ContactSearchOption searchOption;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.theyukicompany.com/", Order=3)]
        public string searchValue;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.theyukicompany.com/", Order=4)]
        public YukiMcp.Yuki.Contact.ContactSortOrder sortOrder;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.theyukicompany.com/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> modifiedAfter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.theyukicompany.com/", Order=6)]
        public YukiMcp.Yuki.Contact.ContactActive active;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.theyukicompany.com/", Order=7)]
        public int pageNumber;
        
        public SearchContactsRequest()
        {
        }
        
        public SearchContactsRequest(string sessionID, string domainID, YukiMcp.Yuki.Contact.ContactSearchOption searchOption, string searchValue, YukiMcp.Yuki.Contact.ContactSortOrder sortOrder, System.Nullable<System.DateTime> modifiedAfter, YukiMcp.Yuki.Contact.ContactActive active, int pageNumber)
        {
            this.sessionID = sessionID;
            this.domainID = domainID;
            this.searchOption = searchOption;
            this.searchValue = searchValue;
            this.sortOrder = sortOrder;
            this.modifiedAfter = modifiedAfter;
            this.active = active;
            this.pageNumber = pageNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchContactsResponse", WrapperNamespace="http://www.theyukicompany.com/", IsWrapped=true)]
    public partial class SearchContactsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.theyukicompany.com/", Order=0)]
        public System.Xml.XmlNode SearchContactsResult;
        
        public SearchContactsResponse()
        {
        }
        
        public SearchContactsResponse(System.Xml.XmlNode SearchContactsResult)
        {
            this.SearchContactsResult = SearchContactsResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.theyukicompany.com/")]
    public enum ContactType
    {
        
        /// <remarks/>
        Customer,
        
        /// <remarks/>
        Supplier,
        
        /// <remarks/>
        Both,
        
        /// <remarks/>
        None,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSuppliersAndCustomers", WrapperNamespace="http://www.theyukicompany.com/", IsWrapped=true)]
    public partial class GetSuppliersAndCustomersRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.theyukicompany.com/", Order=0)]
        public string sessionID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.theyukicompany.com/", Order=1)]
        public string domainID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.theyukicompany.com/", Order=2)]
        public YukiMcp.Yuki.Contact.ContactSearchOption searchOption;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.theyukicompany.com/", Order=3)]
        public string searchValue;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.theyukicompany.com/", Order=4)]
        public YukiMcp.Yuki.Contact.ContactSortOrder sortOrder;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.theyukicompany.com/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> modifiedAfter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.theyukicompany.com/", Order=6)]
        public YukiMcp.Yuki.Contact.ContactActive active;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.theyukicompany.com/", Order=7)]
        public int pageNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.theyukicompany.com/", Order=8)]
        public YukiMcp.Yuki.Contact.ContactType contactType;
        
        public GetSuppliersAndCustomersRequest()
        {
        }
        
        public GetSuppliersAndCustomersRequest(string sessionID, string domainID, YukiMcp.Yuki.Contact.ContactSearchOption searchOption, string searchValue, YukiMcp.Yuki.Contact.ContactSortOrder sortOrder, System.Nullable<System.DateTime> modifiedAfter, YukiMcp.Yuki.Contact.ContactActive active, int pageNumber, YukiMcp.Yuki.Contact.ContactType contactType)
        {
            this.sessionID = sessionID;
            this.domainID = domainID;
            this.searchOption = searchOption;
            this.searchValue = searchValue;
            this.sortOrder = sortOrder;
            this.modifiedAfter = modifiedAfter;
            this.active = active;
            this.pageNumber = pageNumber;
            this.contactType = contactType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSuppliersAndCustomersResponse", WrapperNamespace="http://www.theyukicompany.com/", IsWrapped=true)]
    public partial class GetSuppliersAndCustomersResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.theyukicompany.com/", Order=0)]
        public System.Xml.XmlNode GetSuppliersAndCustomersResult;
        
        public GetSuppliersAndCustomersResponse()
        {
        }
        
        public GetSuppliersAndCustomersResponse(System.Xml.XmlNode GetSuppliersAndCustomersResult)
        {
            this.GetSuppliersAndCustomersResult = GetSuppliersAndCustomersResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface ContactSoapChannel : YukiMcp.Yuki.Contact.ContactSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class ContactSoapClient : System.ServiceModel.ClientBase<YukiMcp.Yuki.Contact.ContactSoap>, YukiMcp.Yuki.Contact.ContactSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ContactSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(ContactSoapClient.GetBindingForEndpoint(endpointConfiguration), ContactSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ContactSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ContactSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ContactSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ContactSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ContactSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YukiMcp.Yuki.Contact.SearchContactsResponse> YukiMcp.Yuki.Contact.ContactSoap.SearchContactsAsync(YukiMcp.Yuki.Contact.SearchContactsRequest request)
        {
            return base.Channel.SearchContactsAsync(request);
        }
        
        public System.Threading.Tasks.Task<YukiMcp.Yuki.Contact.SearchContactsResponse> SearchContactsAsync(string sessionID, string domainID, YukiMcp.Yuki.Contact.ContactSearchOption searchOption, string searchValue, YukiMcp.Yuki.Contact.ContactSortOrder sortOrder, System.Nullable<System.DateTime> modifiedAfter, YukiMcp.Yuki.Contact.ContactActive active, int pageNumber)
        {
            YukiMcp.Yuki.Contact.SearchContactsRequest inValue = new YukiMcp.Yuki.Contact.SearchContactsRequest();
            inValue.sessionID = sessionID;
            inValue.domainID = domainID;
            inValue.searchOption = searchOption;
            inValue.searchValue = searchValue;
            inValue.sortOrder = sortOrder;
            inValue.modifiedAfter = modifiedAfter;
            inValue.active = active;
            inValue.pageNumber = pageNumber;
            return ((YukiMcp.Yuki.Contact.ContactSoap)(this)).SearchContactsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YukiMcp.Yuki.Contact.GetSuppliersAndCustomersResponse> YukiMcp.Yuki.Contact.ContactSoap.GetSuppliersAndCustomersAsync(YukiMcp.Yuki.Contact.GetSuppliersAndCustomersRequest request)
        {
            return base.Channel.GetSuppliersAndCustomersAsync(request);
        }
        
        public System.Threading.Tasks.Task<YukiMcp.Yuki.Contact.GetSuppliersAndCustomersResponse> GetSuppliersAndCustomersAsync(string sessionID, string domainID, YukiMcp.Yuki.Contact.ContactSearchOption searchOption, string searchValue, YukiMcp.Yuki.Contact.ContactSortOrder sortOrder, System.Nullable<System.DateTime> modifiedAfter, YukiMcp.Yuki.Contact.ContactActive active, int pageNumber, YukiMcp.Yuki.Contact.ContactType contactType)
        {
            YukiMcp.Yuki.Contact.GetSuppliersAndCustomersRequest inValue = new YukiMcp.Yuki.Contact.GetSuppliersAndCustomersRequest();
            inValue.sessionID = sessionID;
            inValue.domainID = domainID;
            inValue.searchOption = searchOption;
            inValue.searchValue = searchValue;
            inValue.sortOrder = sortOrder;
            inValue.modifiedAfter = modifiedAfter;
            inValue.active = active;
            inValue.pageNumber = pageNumber;
            inValue.contactType = contactType;
            return ((YukiMcp.Yuki.Contact.ContactSoap)(this)).GetSuppliersAndCustomersAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> UpdateContactAsync(string sessionID, string domainID, System.Xml.XmlNode xmlDoc)
        {
            return base.Channel.UpdateContactAsync(sessionID, domainID, xmlDoc);
        }
        
        public System.Threading.Tasks.Task<string> AuthenticateAsync(string accessKey)
        {
            return base.Channel.AuthenticateAsync(accessKey);
        }
        
        public System.Threading.Tasks.Task<string> AuthenticateClientAsync(string clientID, string clientSecret, string accessKey)
        {
            return base.Channel.AuthenticateClientAsync(clientID, clientSecret, accessKey);
        }
        
        public System.Threading.Tasks.Task<string> AuthenticateByUserNameAsync(string userName, string password)
        {
            return base.Channel.AuthenticateByUserNameAsync(userName, password);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> DomainsAsync(string sessionID)
        {
            return base.Channel.DomainsAsync(sessionID);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> CompaniesAsync(string sessionID)
        {
            return base.Channel.CompaniesAsync(sessionID);
        }
        
        public System.Threading.Tasks.Task<string> AdministrationIDAsync(string sessionID, string administrationName)
        {
            return base.Channel.AdministrationIDAsync(sessionID, administrationName);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> AdministrationsAsync(string sessionID)
        {
            return base.Channel.AdministrationsAsync(sessionID);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> AdministrationsWithInternalCustomerCodeAsync(string sessionID)
        {
            return base.Channel.AdministrationsWithInternalCustomerCodeAsync(sessionID);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetCurrentDomainAsync(string sessionID)
        {
            return base.Channel.GetCurrentDomainAsync(sessionID);
        }
        
        public System.Threading.Tasks.Task SetCurrentDomainAsync(string sessionID, string domainID)
        {
            return base.Channel.SetCurrentDomainAsync(sessionID, domainID);
        }
        
        public System.Threading.Tasks.Task<string> LanguageAsync(string sessionID)
        {
            return base.Channel.LanguageAsync(sessionID);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> SupportedLanguagesAsync(string sessionID)
        {
            return base.Channel.SupportedLanguagesAsync(sessionID);
        }
        
        public System.Threading.Tasks.Task SetLanguageAsync(string sessionID, string language)
        {
            return base.Channel.SetLanguageAsync(sessionID, language);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ContactSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.ContactSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ContactSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://api.yukiworks.be/ws/Contact.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.ContactSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://api.yukiworks.be/ws/Contact.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            ContactSoap,
            
            ContactSoap12,
        }
    }
}
