//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YukiMcp.Yuki.Accounting
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.theyukicompany.com/", ConfigurationName="YukiMcp.Yuki.Accounting.AccountingSoap")]
    public interface AccountingSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/GLAccountBalance", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GLAccountBalanceAsync(string sessionID, string administrationID, System.DateTime transactionDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/GLAccountBalanceFiscal", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GLAccountBalanceFiscalAsync(string sessionID, string administrationID, System.DateTime transactionDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/GLAccountBalanceYearEnd", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GLAccountBalanceYearEndAsync(string sessionID, string administrationID, System.DateTime transactionDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/GLAccountTransactions", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GLAccountTransactionsAsync(string sessionID, string administrationID, string GLAccountCode, System.DateTime StartDate, System.DateTime EndDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/GLAccountTransactionsAndContact", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GLAccountTransactionsAndContactAsync(string sessionID, string administrationID, string GLAccountCode, System.DateTime StartDate, System.DateTime EndDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/GLAccountTransactionsFiscal", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GLAccountTransactionsFiscalAsync(string sessionID, string administrationID, string GLAccountCode, System.DateTime StartDate, System.DateTime EndDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/NetRevenue", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<decimal> NetRevenueAsync(string sessionID, string administrationID, System.DateTime StartDate, System.DateTime EndDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/NetRevenueFiscal", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<decimal> NetRevenueFiscalAsync(string sessionID, string administrationID, System.DateTime StartDate, System.DateTime EndDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/OutstandingCreditorItems", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> OutstandingCreditorItemsAsync(string sessionID, string administrationID, bool includeBankTransactions, YukiMcp.Yuki.Accounting.OutstandingItemsSortOrder sortOrder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/OutstandingCreditorItemsByDateOutstanding", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> OutstandingCreditorItemsByDateOutstandingAsync(string sessionID, string administrationID, bool includeBankTransactions, YukiMcp.Yuki.Accounting.OutstandingItemsSortOrder sortOrder, System.DateTime dateOutstanding);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/OutstandingCreditorItemsByDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> OutstandingCreditorItemsByDateAsync(string sessionID, string administrationID, bool includeBankTransactions, YukiMcp.Yuki.Accounting.OutstandingItemsSortOrder sortOrder, System.DateTime startDate, System.DateTime endDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/OutstandingCreditorWithPaymentReference", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> OutstandingCreditorWithPaymentReferenceAsync(string sessionID, string administrationID, bool includeBankTransactions, YukiMcp.Yuki.Accounting.OutstandingItemsSortOrder sortOrder, System.DateTime startDate, System.DateTime endDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/OutstandingDebtorItems", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> OutstandingDebtorItemsAsync(string sessionID, string administrationID, bool includeBankTransactions, YukiMcp.Yuki.Accounting.OutstandingItemsSortOrder sortOrder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/OutstandingDebtorItemsByDateOutstanding", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> OutstandingDebtorItemsByDateOutstandingAsync(string sessionID, string administrationID, bool includeBankTransactions, YukiMcp.Yuki.Accounting.OutstandingItemsSortOrder sortOrder, System.DateTime dateOutstanding);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/OutstandingDebtorItemsWithLanguage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> OutstandingDebtorItemsWithLanguageAsync(string sessionID, string administrationID, bool includeBankTransactions, YukiMcp.Yuki.Accounting.OutstandingItemsSortOrder sortOrder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/OutstandingDebtorItemsByDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> OutstandingDebtorItemsByDateAsync(string sessionID, string administrationID, bool includeBankTransactions, YukiMcp.Yuki.Accounting.OutstandingItemsSortOrder sortOrder, System.DateTime startDate, System.DateTime endDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/OutstandingDebtorWithPaymentReference", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> OutstandingDebtorWithPaymentReferenceAsync(string sessionID, string administrationID, bool includeBankTransactions, YukiMcp.Yuki.Accounting.OutstandingItemsSortOrder sortOrder, System.DateTime startDate, System.DateTime endDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/CheckOutstandingItem", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> CheckOutstandingItemAsync(string sessionID, string Reference);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/CheckOutstandingItemAdmin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> CheckOutstandingItemAdminAsync(string sessionID, string administrationID, string Reference);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/ProcessJournal", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> ProcessJournalAsync(string sessionID, string administrationID, System.Xml.XmlNode xmlDoc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/Authenticate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> AuthenticateAsync(string accessKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/AuthenticateClient", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> AuthenticateClientAsync(string clientID, string clientSecret, string accessKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/AuthenticateByUserName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> AuthenticateByUserNameAsync(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/Domains", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> DomainsAsync(string sessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/Companies", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> CompaniesAsync(string sessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/AdministrationID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> AdministrationIDAsync(string sessionID, string administrationName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/Administrations", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> AdministrationsAsync(string sessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/AdministrationsWithInternalCustomerCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> AdministrationsWithInternalCustomerCodeAsync(string sessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/GetCurrentDomain", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetCurrentDomainAsync(string sessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/SetCurrentDomain", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task SetCurrentDomainAsync(string sessionID, string domainID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/Language", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> LanguageAsync(string sessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/SupportedLanguages", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> SupportedLanguagesAsync(string sessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/SetLanguage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task SetLanguageAsync(string sessionID, string language);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.theyukicompany.com/")]
    public enum OutstandingItemsSortOrder
    {
        
        /// <remarks/>
        ContactAsc,
        
        /// <remarks/>
        ContactDesc,
        
        /// <remarks/>
        AmountAsc,
        
        /// <remarks/>
        AmountDesc,
        
        /// <remarks/>
        DateAsc,
        
        /// <remarks/>
        DateDesc,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface AccountingSoapChannel : YukiMcp.Yuki.Accounting.AccountingSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class AccountingSoapClient : System.ServiceModel.ClientBase<YukiMcp.Yuki.Accounting.AccountingSoap>, YukiMcp.Yuki.Accounting.AccountingSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public AccountingSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(AccountingSoapClient.GetBindingForEndpoint(endpointConfiguration), AccountingSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AccountingSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(AccountingSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AccountingSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(AccountingSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AccountingSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GLAccountBalanceAsync(string sessionID, string administrationID, System.DateTime transactionDate)
        {
            return base.Channel.GLAccountBalanceAsync(sessionID, administrationID, transactionDate);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GLAccountBalanceFiscalAsync(string sessionID, string administrationID, System.DateTime transactionDate)
        {
            return base.Channel.GLAccountBalanceFiscalAsync(sessionID, administrationID, transactionDate);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GLAccountBalanceYearEndAsync(string sessionID, string administrationID, System.DateTime transactionDate)
        {
            return base.Channel.GLAccountBalanceYearEndAsync(sessionID, administrationID, transactionDate);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GLAccountTransactionsAsync(string sessionID, string administrationID, string GLAccountCode, System.DateTime StartDate, System.DateTime EndDate)
        {
            return base.Channel.GLAccountTransactionsAsync(sessionID, administrationID, GLAccountCode, StartDate, EndDate);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GLAccountTransactionsAndContactAsync(string sessionID, string administrationID, string GLAccountCode, System.DateTime StartDate, System.DateTime EndDate)
        {
            return base.Channel.GLAccountTransactionsAndContactAsync(sessionID, administrationID, GLAccountCode, StartDate, EndDate);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GLAccountTransactionsFiscalAsync(string sessionID, string administrationID, string GLAccountCode, System.DateTime StartDate, System.DateTime EndDate)
        {
            return base.Channel.GLAccountTransactionsFiscalAsync(sessionID, administrationID, GLAccountCode, StartDate, EndDate);
        }
        
        public System.Threading.Tasks.Task<decimal> NetRevenueAsync(string sessionID, string administrationID, System.DateTime StartDate, System.DateTime EndDate)
        {
            return base.Channel.NetRevenueAsync(sessionID, administrationID, StartDate, EndDate);
        }
        
        public System.Threading.Tasks.Task<decimal> NetRevenueFiscalAsync(string sessionID, string administrationID, System.DateTime StartDate, System.DateTime EndDate)
        {
            return base.Channel.NetRevenueFiscalAsync(sessionID, administrationID, StartDate, EndDate);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> OutstandingCreditorItemsAsync(string sessionID, string administrationID, bool includeBankTransactions, YukiMcp.Yuki.Accounting.OutstandingItemsSortOrder sortOrder)
        {
            return base.Channel.OutstandingCreditorItemsAsync(sessionID, administrationID, includeBankTransactions, sortOrder);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> OutstandingCreditorItemsByDateOutstandingAsync(string sessionID, string administrationID, bool includeBankTransactions, YukiMcp.Yuki.Accounting.OutstandingItemsSortOrder sortOrder, System.DateTime dateOutstanding)
        {
            return base.Channel.OutstandingCreditorItemsByDateOutstandingAsync(sessionID, administrationID, includeBankTransactions, sortOrder, dateOutstanding);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> OutstandingCreditorItemsByDateAsync(string sessionID, string administrationID, bool includeBankTransactions, YukiMcp.Yuki.Accounting.OutstandingItemsSortOrder sortOrder, System.DateTime startDate, System.DateTime endDate)
        {
            return base.Channel.OutstandingCreditorItemsByDateAsync(sessionID, administrationID, includeBankTransactions, sortOrder, startDate, endDate);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> OutstandingCreditorWithPaymentReferenceAsync(string sessionID, string administrationID, bool includeBankTransactions, YukiMcp.Yuki.Accounting.OutstandingItemsSortOrder sortOrder, System.DateTime startDate, System.DateTime endDate)
        {
            return base.Channel.OutstandingCreditorWithPaymentReferenceAsync(sessionID, administrationID, includeBankTransactions, sortOrder, startDate, endDate);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> OutstandingDebtorItemsAsync(string sessionID, string administrationID, bool includeBankTransactions, YukiMcp.Yuki.Accounting.OutstandingItemsSortOrder sortOrder)
        {
            return base.Channel.OutstandingDebtorItemsAsync(sessionID, administrationID, includeBankTransactions, sortOrder);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> OutstandingDebtorItemsByDateOutstandingAsync(string sessionID, string administrationID, bool includeBankTransactions, YukiMcp.Yuki.Accounting.OutstandingItemsSortOrder sortOrder, System.DateTime dateOutstanding)
        {
            return base.Channel.OutstandingDebtorItemsByDateOutstandingAsync(sessionID, administrationID, includeBankTransactions, sortOrder, dateOutstanding);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> OutstandingDebtorItemsWithLanguageAsync(string sessionID, string administrationID, bool includeBankTransactions, YukiMcp.Yuki.Accounting.OutstandingItemsSortOrder sortOrder)
        {
            return base.Channel.OutstandingDebtorItemsWithLanguageAsync(sessionID, administrationID, includeBankTransactions, sortOrder);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> OutstandingDebtorItemsByDateAsync(string sessionID, string administrationID, bool includeBankTransactions, YukiMcp.Yuki.Accounting.OutstandingItemsSortOrder sortOrder, System.DateTime startDate, System.DateTime endDate)
        {
            return base.Channel.OutstandingDebtorItemsByDateAsync(sessionID, administrationID, includeBankTransactions, sortOrder, startDate, endDate);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> OutstandingDebtorWithPaymentReferenceAsync(string sessionID, string administrationID, bool includeBankTransactions, YukiMcp.Yuki.Accounting.OutstandingItemsSortOrder sortOrder, System.DateTime startDate, System.DateTime endDate)
        {
            return base.Channel.OutstandingDebtorWithPaymentReferenceAsync(sessionID, administrationID, includeBankTransactions, sortOrder, startDate, endDate);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> CheckOutstandingItemAsync(string sessionID, string Reference)
        {
            return base.Channel.CheckOutstandingItemAsync(sessionID, Reference);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> CheckOutstandingItemAdminAsync(string sessionID, string administrationID, string Reference)
        {
            return base.Channel.CheckOutstandingItemAdminAsync(sessionID, administrationID, Reference);
        }
        
        public System.Threading.Tasks.Task<string> ProcessJournalAsync(string sessionID, string administrationID, System.Xml.XmlNode xmlDoc)
        {
            return base.Channel.ProcessJournalAsync(sessionID, administrationID, xmlDoc);
        }
        
        public System.Threading.Tasks.Task<string> AuthenticateAsync(string accessKey)
        {
            return base.Channel.AuthenticateAsync(accessKey);
        }
        
        public System.Threading.Tasks.Task<string> AuthenticateClientAsync(string clientID, string clientSecret, string accessKey)
        {
            return base.Channel.AuthenticateClientAsync(clientID, clientSecret, accessKey);
        }
        
        public System.Threading.Tasks.Task<string> AuthenticateByUserNameAsync(string userName, string password)
        {
            return base.Channel.AuthenticateByUserNameAsync(userName, password);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> DomainsAsync(string sessionID)
        {
            return base.Channel.DomainsAsync(sessionID);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> CompaniesAsync(string sessionID)
        {
            return base.Channel.CompaniesAsync(sessionID);
        }
        
        public System.Threading.Tasks.Task<string> AdministrationIDAsync(string sessionID, string administrationName)
        {
            return base.Channel.AdministrationIDAsync(sessionID, administrationName);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> AdministrationsAsync(string sessionID)
        {
            return base.Channel.AdministrationsAsync(sessionID);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> AdministrationsWithInternalCustomerCodeAsync(string sessionID)
        {
            return base.Channel.AdministrationsWithInternalCustomerCodeAsync(sessionID);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetCurrentDomainAsync(string sessionID)
        {
            return base.Channel.GetCurrentDomainAsync(sessionID);
        }
        
        public System.Threading.Tasks.Task SetCurrentDomainAsync(string sessionID, string domainID)
        {
            return base.Channel.SetCurrentDomainAsync(sessionID, domainID);
        }
        
        public System.Threading.Tasks.Task<string> LanguageAsync(string sessionID)
        {
            return base.Channel.LanguageAsync(sessionID);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> SupportedLanguagesAsync(string sessionID)
        {
            return base.Channel.SupportedLanguagesAsync(sessionID);
        }
        
        public System.Threading.Tasks.Task SetLanguageAsync(string sessionID, string language)
        {
            return base.Channel.SetLanguageAsync(sessionID, language);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AccountingSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.AccountingSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AccountingSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://api.yukiworks.be/ws/Accounting.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.AccountingSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://api.yukiworks.be/ws/Accounting.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            AccountingSoap,
            
            AccountingSoap12,
        }
    }
}
