//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YukiMcp.Yuki.ChangeDigest
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.theyukicompany.com/", ConfigurationName="YukiMcp.Yuki.ChangeDigest.ChangeDigestSoap")]
    public interface ChangeDigestSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/GetUpdatedAndDeletedTransactions", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<YukiMcp.Yuki.ChangeDigest.GetUpdatedAndDeletedTransactionsResponse> GetUpdatedAndDeletedTransactionsAsync(YukiMcp.Yuki.ChangeDigest.GetUpdatedAndDeletedTransactionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/GetTransactionDetail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<YukiMcp.Yuki.ChangeDigest.TransactionInfo> GetTransactionDetailAsync(string sessionID, string administrationID, string transactionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/Authenticate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> AuthenticateAsync(string accessKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/AuthenticateClient", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> AuthenticateClientAsync(string clientID, string clientSecret, string accessKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/AuthenticateByUserName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> AuthenticateByUserNameAsync(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/Domains", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> DomainsAsync(string sessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/Companies", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> CompaniesAsync(string sessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/AdministrationID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> AdministrationIDAsync(string sessionID, string administrationName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/Administrations", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> AdministrationsAsync(string sessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/AdministrationsWithInternalCustomerCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> AdministrationsWithInternalCustomerCodeAsync(string sessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/GetCurrentDomain", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetCurrentDomainAsync(string sessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/SetCurrentDomain", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task SetCurrentDomainAsync(string sessionID, string domainID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/Language", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> LanguageAsync(string sessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/SupportedLanguages", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> SupportedLanguagesAsync(string sessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/SetLanguage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task SetLanguageAsync(string sessionID, string language);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.theyukicompany.com/")]
    public partial class UpdatedTransaction
    {
        
        private string idField;
        
        private System.DateTime transactionDateField;
        
        private string descriptionField;
        
        private decimal transactionAmountField;
        
        private decimal transactionAmountForeignCurrencyField;
        
        private decimal currencyRateField;
        
        private string currencyField;
        
        private string contactIDField;
        
        private string fullNameField;
        
        private string glAccountCodeField;
        
        private string documentIDField;
        
        private string projectField;
        
        private string projectCodeField;
        
        private System.DateTime createdField;
        
        private System.DateTime updatedField;
        
        private string deletedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime transactionDate
        {
            get
            {
                return this.transactionDateField;
            }
            set
            {
                this.transactionDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal transactionAmount
        {
            get
            {
                return this.transactionAmountField;
            }
            set
            {
                this.transactionAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal transactionAmountForeignCurrency
        {
            get
            {
                return this.transactionAmountForeignCurrencyField;
            }
            set
            {
                this.transactionAmountForeignCurrencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public decimal currencyRate
        {
            get
            {
                return this.currencyRateField;
            }
            set
            {
                this.currencyRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string currency
        {
            get
            {
                return this.currencyField;
            }
            set
            {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string contactID
        {
            get
            {
                return this.contactIDField;
            }
            set
            {
                this.contactIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string fullName
        {
            get
            {
                return this.fullNameField;
            }
            set
            {
                this.fullNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string glAccountCode
        {
            get
            {
                return this.glAccountCodeField;
            }
            set
            {
                this.glAccountCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string documentID
        {
            get
            {
                return this.documentIDField;
            }
            set
            {
                this.documentIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string project
        {
            get
            {
                return this.projectField;
            }
            set
            {
                this.projectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string projectCode
        {
            get
            {
                return this.projectCodeField;
            }
            set
            {
                this.projectCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public System.DateTime created
        {
            get
            {
                return this.createdField;
            }
            set
            {
                this.createdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public System.DateTime updated
        {
            get
            {
                return this.updatedField;
            }
            set
            {
                this.updatedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string deleted
        {
            get
            {
                return this.deletedField;
            }
            set
            {
                this.deletedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.theyukicompany.com/")]
    public partial class TransactionInfo
    {
        
        private string idField;
        
        private int hIDField;
        
        private System.DateTime transactionDateField;
        
        private string descriptionField;
        
        private decimal transactionAmountField;
        
        private decimal transactionAmountForeignCurrencyField;
        
        private decimal currencyRateField;
        
        private string currencyField;
        
        private string taxCodeDescriptionField;
        
        private string fullNameField;
        
        private string coCNumberField;
        
        private string vATNumberField;
        
        private System.Nullable<int> contactHIDField;
        
        private string contactCodeField;
        
        private string contactCountryField;
        
        private string contactZipCodeField;
        
        private string projectField;
        
        private string projectCodeField;
        
        private string glAccountCodeField;
        
        private string documentIDField;
        
        private string documentReferenceField;
        
        private string documentTypeField;
        
        private string documentFolderField;
        
        private string documentFolderTabField;
        
        private string contactIDField;
        
        private string periodIdField;
        
        private string companyField;
        
        private string mutationUserField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int hID
        {
            get
            {
                return this.hIDField;
            }
            set
            {
                this.hIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime transactionDate
        {
            get
            {
                return this.transactionDateField;
            }
            set
            {
                this.transactionDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal transactionAmount
        {
            get
            {
                return this.transactionAmountField;
            }
            set
            {
                this.transactionAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public decimal transactionAmountForeignCurrency
        {
            get
            {
                return this.transactionAmountForeignCurrencyField;
            }
            set
            {
                this.transactionAmountForeignCurrencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public decimal currencyRate
        {
            get
            {
                return this.currencyRateField;
            }
            set
            {
                this.currencyRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string currency
        {
            get
            {
                return this.currencyField;
            }
            set
            {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string taxCodeDescription
        {
            get
            {
                return this.taxCodeDescriptionField;
            }
            set
            {
                this.taxCodeDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string fullName
        {
            get
            {
                return this.fullNameField;
            }
            set
            {
                this.fullNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string CoCNumber
        {
            get
            {
                return this.coCNumberField;
            }
            set
            {
                this.coCNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string VATNumber
        {
            get
            {
                return this.vATNumberField;
            }
            set
            {
                this.vATNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public System.Nullable<int> contactHID
        {
            get
            {
                return this.contactHIDField;
            }
            set
            {
                this.contactHIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string contactCode
        {
            get
            {
                return this.contactCodeField;
            }
            set
            {
                this.contactCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string contactCountry
        {
            get
            {
                return this.contactCountryField;
            }
            set
            {
                this.contactCountryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string contactZipCode
        {
            get
            {
                return this.contactZipCodeField;
            }
            set
            {
                this.contactZipCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string project
        {
            get
            {
                return this.projectField;
            }
            set
            {
                this.projectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string projectCode
        {
            get
            {
                return this.projectCodeField;
            }
            set
            {
                this.projectCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string glAccountCode
        {
            get
            {
                return this.glAccountCodeField;
            }
            set
            {
                this.glAccountCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string documentID
        {
            get
            {
                return this.documentIDField;
            }
            set
            {
                this.documentIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string documentReference
        {
            get
            {
                return this.documentReferenceField;
            }
            set
            {
                this.documentReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string documentType
        {
            get
            {
                return this.documentTypeField;
            }
            set
            {
                this.documentTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string documentFolder
        {
            get
            {
                return this.documentFolderField;
            }
            set
            {
                this.documentFolderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string documentFolderTab
        {
            get
            {
                return this.documentFolderTabField;
            }
            set
            {
                this.documentFolderTabField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string contactID
        {
            get
            {
                return this.contactIDField;
            }
            set
            {
                this.contactIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string periodId
        {
            get
            {
                return this.periodIdField;
            }
            set
            {
                this.periodIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string company
        {
            get
            {
                return this.companyField;
            }
            set
            {
                this.companyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string mutationUser
        {
            get
            {
                return this.mutationUserField;
            }
            set
            {
                this.mutationUserField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUpdatedAndDeletedTransactions", WrapperNamespace="http://www.theyukicompany.com/", IsWrapped=true)]
    public partial class GetUpdatedAndDeletedTransactionsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.theyukicompany.com/", Order=0)]
        public string sessionID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.theyukicompany.com/", Order=1)]
        public string administrationID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.theyukicompany.com/", Order=2)]
        public System.DateTime startDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.theyukicompany.com/", Order=3)]
        public System.DateTime endDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.theyukicompany.com/", Order=4)]
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int numberOfRecords;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.theyukicompany.com/", Order=5)]
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int startRecord;
        
        public GetUpdatedAndDeletedTransactionsRequest()
        {
        }
        
        public GetUpdatedAndDeletedTransactionsRequest(string sessionID, string administrationID, System.DateTime startDate, System.DateTime endDate, int numberOfRecords, int startRecord)
        {
            this.sessionID = sessionID;
            this.administrationID = administrationID;
            this.startDate = startDate;
            this.endDate = endDate;
            this.numberOfRecords = numberOfRecords;
            this.startRecord = startRecord;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUpdatedAndDeletedTransactionsResponse", WrapperNamespace="http://www.theyukicompany.com/", IsWrapped=true)]
    public partial class GetUpdatedAndDeletedTransactionsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.theyukicompany.com/", Order=0)]
        public YukiMcp.Yuki.ChangeDigest.UpdatedTransaction[] GetUpdatedAndDeletedTransactionsResult;
        
        public GetUpdatedAndDeletedTransactionsResponse()
        {
        }
        
        public GetUpdatedAndDeletedTransactionsResponse(YukiMcp.Yuki.ChangeDigest.UpdatedTransaction[] GetUpdatedAndDeletedTransactionsResult)
        {
            this.GetUpdatedAndDeletedTransactionsResult = GetUpdatedAndDeletedTransactionsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface ChangeDigestSoapChannel : YukiMcp.Yuki.ChangeDigest.ChangeDigestSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class ChangeDigestSoapClient : System.ServiceModel.ClientBase<YukiMcp.Yuki.ChangeDigest.ChangeDigestSoap>, YukiMcp.Yuki.ChangeDigest.ChangeDigestSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ChangeDigestSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(ChangeDigestSoapClient.GetBindingForEndpoint(endpointConfiguration), ChangeDigestSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ChangeDigestSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ChangeDigestSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ChangeDigestSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ChangeDigestSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ChangeDigestSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YukiMcp.Yuki.ChangeDigest.GetUpdatedAndDeletedTransactionsResponse> YukiMcp.Yuki.ChangeDigest.ChangeDigestSoap.GetUpdatedAndDeletedTransactionsAsync(YukiMcp.Yuki.ChangeDigest.GetUpdatedAndDeletedTransactionsRequest request)
        {
            return base.Channel.GetUpdatedAndDeletedTransactionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<YukiMcp.Yuki.ChangeDigest.GetUpdatedAndDeletedTransactionsResponse> GetUpdatedAndDeletedTransactionsAsync(string sessionID, string administrationID, System.DateTime startDate, System.DateTime endDate, int numberOfRecords, int startRecord)
        {
            YukiMcp.Yuki.ChangeDigest.GetUpdatedAndDeletedTransactionsRequest inValue = new YukiMcp.Yuki.ChangeDigest.GetUpdatedAndDeletedTransactionsRequest();
            inValue.sessionID = sessionID;
            inValue.administrationID = administrationID;
            inValue.startDate = startDate;
            inValue.endDate = endDate;
            inValue.numberOfRecords = numberOfRecords;
            inValue.startRecord = startRecord;
            return ((YukiMcp.Yuki.ChangeDigest.ChangeDigestSoap)(this)).GetUpdatedAndDeletedTransactionsAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<YukiMcp.Yuki.ChangeDigest.TransactionInfo> GetTransactionDetailAsync(string sessionID, string administrationID, string transactionID)
        {
            return base.Channel.GetTransactionDetailAsync(sessionID, administrationID, transactionID);
        }
        
        public System.Threading.Tasks.Task<string> AuthenticateAsync(string accessKey)
        {
            return base.Channel.AuthenticateAsync(accessKey);
        }
        
        public System.Threading.Tasks.Task<string> AuthenticateClientAsync(string clientID, string clientSecret, string accessKey)
        {
            return base.Channel.AuthenticateClientAsync(clientID, clientSecret, accessKey);
        }
        
        public System.Threading.Tasks.Task<string> AuthenticateByUserNameAsync(string userName, string password)
        {
            return base.Channel.AuthenticateByUserNameAsync(userName, password);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> DomainsAsync(string sessionID)
        {
            return base.Channel.DomainsAsync(sessionID);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> CompaniesAsync(string sessionID)
        {
            return base.Channel.CompaniesAsync(sessionID);
        }
        
        public System.Threading.Tasks.Task<string> AdministrationIDAsync(string sessionID, string administrationName)
        {
            return base.Channel.AdministrationIDAsync(sessionID, administrationName);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> AdministrationsAsync(string sessionID)
        {
            return base.Channel.AdministrationsAsync(sessionID);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> AdministrationsWithInternalCustomerCodeAsync(string sessionID)
        {
            return base.Channel.AdministrationsWithInternalCustomerCodeAsync(sessionID);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetCurrentDomainAsync(string sessionID)
        {
            return base.Channel.GetCurrentDomainAsync(sessionID);
        }
        
        public System.Threading.Tasks.Task SetCurrentDomainAsync(string sessionID, string domainID)
        {
            return base.Channel.SetCurrentDomainAsync(sessionID, domainID);
        }
        
        public System.Threading.Tasks.Task<string> LanguageAsync(string sessionID)
        {
            return base.Channel.LanguageAsync(sessionID);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> SupportedLanguagesAsync(string sessionID)
        {
            return base.Channel.SupportedLanguagesAsync(sessionID);
        }
        
        public System.Threading.Tasks.Task SetLanguageAsync(string sessionID, string language)
        {
            return base.Channel.SetLanguageAsync(sessionID, language);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ChangeDigestSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.ChangeDigestSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ChangeDigestSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://api.yukiworks.be/ws/ChangeDigest.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.ChangeDigestSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://api.yukiworks.be/ws/ChangeDigest.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            ChangeDigestSoap,
            
            ChangeDigestSoap12,
        }
    }
}
