//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YukiMcp.Yuki.AccountingInfo
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.theyukicompany.com/", ConfigurationName="YukiMcp.Yuki.AccountingInfo.AccountingInfoSoap")]
    public interface AccountingInfoSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/GetGLAccountScheme", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<YukiMcp.Yuki.AccountingInfo.GlAccount[]> GetGLAccountSchemeAsync(string sessionID, string administrationID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/GetCustomPaymentMethods", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<YukiMcp.Yuki.AccountingInfo.PaymentMethod[]> GetCustomPaymentMethodsAsync(string sessionID, string administrationID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/GetRGSScheme", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<YukiMcp.Yuki.AccountingInfo.RGSEntry[]> GetRGSSchemeAsync(string sessionID, string administrationID, string rgsVersion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/GetPeriodDateTable", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<YukiMcp.Yuki.AccountingInfo.AdministrationPeriod> GetPeriodDateTableAsync(string sessionID, string administrationID, int yearID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/GetFinancialYearModifiedDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.DateTime> GetFinancialYearModifiedDateAsync(string sessionID, string administrationID, int yearID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/GetStartBalanceByGlAccount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<YukiMcp.Yuki.AccountingInfo.AccountStartBalance[]> GetStartBalanceByGlAccountAsync(string sessionID, string administrationID, int bookyear, int financialMode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/GetTransactionDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<YukiMcp.Yuki.AccountingInfo.TransactionInfo[]> GetTransactionDetailsAsync(string sessionID, string administrationID, string GLAccountCode, System.DateTime StartDate, System.DateTime EndDate, int financialMode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/GetTransactionDocument", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<YukiMcp.Yuki.AccountingInfo.TransactionDocument> GetTransactionDocumentAsync(string sessionID, string administrationID, string transactionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/GetContactDefaultValues", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<YukiMcp.Yuki.AccountingInfo.ContactDefaultValues[]> GetContactDefaultValuesAsync(string sessionID, string administrationID, string contactID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/GetTransactions", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<YukiMcp.Yuki.AccountingInfo.GetTransactionsResponse> GetTransactionsAsync(YukiMcp.Yuki.AccountingInfo.GetTransactionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/GetProjectBalance", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<YukiMcp.Yuki.AccountingInfo.ProjectBalance[]> GetProjectBalanceAsync(string sessionID, string administrationID, string GLAccountCode, string projectCode, System.DateTime StartDate, System.DateTime EndDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/GetProjects", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<YukiMcp.Yuki.AccountingInfo.Project[]> GetProjectsAsync(string sessionID, string administrationID, YukiMcp.Yuki.AccountingInfo.ProjectSearchOption searchOption, string searchValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/GetProjectsAndID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<YukiMcp.Yuki.AccountingInfo.Project[]> GetProjectsAndIDAsync(string sessionID, string administrationID, YukiMcp.Yuki.AccountingInfo.ProjectSearchOption searchOption, string searchValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/Authenticate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> AuthenticateAsync(string accessKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/AuthenticateClient", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> AuthenticateClientAsync(string clientID, string clientSecret, string accessKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/AuthenticateByUserName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> AuthenticateByUserNameAsync(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/Domains", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> DomainsAsync(string sessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/Companies", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> CompaniesAsync(string sessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/AdministrationID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> AdministrationIDAsync(string sessionID, string administrationName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/Administrations", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> AdministrationsAsync(string sessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/AdministrationsWithInternalCustomerCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> AdministrationsWithInternalCustomerCodeAsync(string sessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/GetCurrentDomain", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetCurrentDomainAsync(string sessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/SetCurrentDomain", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task SetCurrentDomainAsync(string sessionID, string domainID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/Language", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> LanguageAsync(string sessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/SupportedLanguages", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> SupportedLanguagesAsync(string sessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.theyukicompany.com/SetLanguage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task SetLanguageAsync(string sessionID, string language);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.theyukicompany.com/")]
    public partial class GlAccount
    {
        
        private string codeField;
        
        private int typeField;
        
        private int subtypeField;
        
        private bool isEnabledField;
        
        private string descriptonField;
        
        private string descriptionNLField;
        
        private string descriptionFRField;
        
        private string descriptionENField;
        
        private bool isVATApplicableField;
        
        private decimal deductableVATPercentageField;
        
        private decimal professionalPercentageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int subtype
        {
            get
            {
                return this.subtypeField;
            }
            set
            {
                this.subtypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool isEnabled
        {
            get
            {
                return this.isEnabledField;
            }
            set
            {
                this.isEnabledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string descripton
        {
            get
            {
                return this.descriptonField;
            }
            set
            {
                this.descriptonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string descriptionNL
        {
            get
            {
                return this.descriptionNLField;
            }
            set
            {
                this.descriptionNLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string descriptionFR
        {
            get
            {
                return this.descriptionFRField;
            }
            set
            {
                this.descriptionFRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string descriptionEN
        {
            get
            {
                return this.descriptionENField;
            }
            set
            {
                this.descriptionENField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public bool isVATApplicable
        {
            get
            {
                return this.isVATApplicableField;
            }
            set
            {
                this.isVATApplicableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public decimal deductableVATPercentage
        {
            get
            {
                return this.deductableVATPercentageField;
            }
            set
            {
                this.deductableVATPercentageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public decimal professionalPercentage
        {
            get
            {
                return this.professionalPercentageField;
            }
            set
            {
                this.professionalPercentageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.theyukicompany.com/")]
    public partial class Project
    {
        
        private string descriptionField;
        
        private int hIDField;
        
        private string codeField;
        
        private System.DateTime startDateField;
        
        private System.DateTime endDateField;
        
        private string companyField;
        
        private string contactField;
        
        private string tagsField;
        
        private decimal budgetSalesField;
        
        private decimal budgetPurchaseField;
        
        private string contactIDField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int HID
        {
            get
            {
                return this.hIDField;
            }
            set
            {
                this.hIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime startDate
        {
            get
            {
                return this.startDateField;
            }
            set
            {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime endDate
        {
            get
            {
                return this.endDateField;
            }
            set
            {
                this.endDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string company
        {
            get
            {
                return this.companyField;
            }
            set
            {
                this.companyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string contact
        {
            get
            {
                return this.contactField;
            }
            set
            {
                this.contactField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string tags
        {
            get
            {
                return this.tagsField;
            }
            set
            {
                this.tagsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public decimal budgetSales
        {
            get
            {
                return this.budgetSalesField;
            }
            set
            {
                this.budgetSalesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public decimal budgetPurchase
        {
            get
            {
                return this.budgetPurchaseField;
            }
            set
            {
                this.budgetPurchaseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string contactID
        {
            get
            {
                return this.contactIDField;
            }
            set
            {
                this.contactIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.theyukicompany.com/")]
    public partial class ProjectBalance
    {
        
        private string glAccountCodeField;
        
        private string projectField;
        
        private string projectCodeField;
        
        private decimal amountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string glAccountCode
        {
            get
            {
                return this.glAccountCodeField;
            }
            set
            {
                this.glAccountCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string project
        {
            get
            {
                return this.projectField;
            }
            set
            {
                this.projectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string projectCode
        {
            get
            {
                return this.projectCodeField;
            }
            set
            {
                this.projectCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.theyukicompany.com/")]
    public partial class ProjectInfo
    {
        
        private string codeField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.theyukicompany.com/")]
    public partial class VAT
    {
        
        private System.Nullable<short> codeTypeField;
        
        private string codeDescriptionField;
        
        private System.Nullable<decimal> codePercentageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<short> codeType
        {
            get
            {
                return this.codeTypeField;
            }
            set
            {
                this.codeTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string codeDescription
        {
            get
            {
                return this.codeDescriptionField;
            }
            set
            {
                this.codeDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<decimal> codePercentage
        {
            get
            {
                return this.codePercentageField;
            }
            set
            {
                this.codePercentageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.theyukicompany.com/")]
    public partial class ForeignCurrency
    {
        
        private decimal amountFCField;
        
        private decimal rateField;
        
        private string currencyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public decimal amountFC
        {
            get
            {
                return this.amountFCField;
            }
            set
            {
                this.amountFCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public decimal rate
        {
            get
            {
                return this.rateField;
            }
            set
            {
                this.rateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string currency
        {
            get
            {
                return this.currencyField;
            }
            set
            {
                this.currencyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.theyukicompany.com/")]
    public partial class DocumentMatched
    {
        
        private System.Nullable<System.DateTime> matchDateField;
        
        private string matchedByField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<System.DateTime> matchDate
        {
            get
            {
                return this.matchDateField;
            }
            set
            {
                this.matchDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string matchedBy
        {
            get
            {
                return this.matchedByField;
            }
            set
            {
                this.matchedByField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.theyukicompany.com/")]
    public partial class DocumentProcessed
    {
        
        private System.Nullable<System.DateTime> processedDateField;
        
        private string processedByField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<System.DateTime> processedDate
        {
            get
            {
                return this.processedDateField;
            }
            set
            {
                this.processedDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string processedBy
        {
            get
            {
                return this.processedByField;
            }
            set
            {
                this.processedByField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.theyukicompany.com/")]
    public partial class Document
    {
        
        private int hIDField;
        
        private string referenceField;
        
        private string typeField;
        
        private string typeDescriptionField;
        
        private System.Nullable<int> folderIdField;
        
        private string folderField;
        
        private System.Nullable<int> folderTabIdField;
        
        private string folderTabField;
        
        private System.DateTime createdField;
        
        private System.Nullable<System.DateTime> modifiedField;
        
        private string uploadMethodField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int HID
        {
            get
            {
                return this.hIDField;
            }
            set
            {
                this.hIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string reference
        {
            get
            {
                return this.referenceField;
            }
            set
            {
                this.referenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string typeDescription
        {
            get
            {
                return this.typeDescriptionField;
            }
            set
            {
                this.typeDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<int> folderId
        {
            get
            {
                return this.folderIdField;
            }
            set
            {
                this.folderIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string folder
        {
            get
            {
                return this.folderField;
            }
            set
            {
                this.folderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<int> folderTabId
        {
            get
            {
                return this.folderTabIdField;
            }
            set
            {
                this.folderTabIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string folderTab
        {
            get
            {
                return this.folderTabField;
            }
            set
            {
                this.folderTabField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public System.DateTime created
        {
            get
            {
                return this.createdField;
            }
            set
            {
                this.createdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<System.DateTime> modified
        {
            get
            {
                return this.modifiedField;
            }
            set
            {
                this.modifiedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string uploadMethod
        {
            get
            {
                return this.uploadMethodField;
            }
            set
            {
                this.uploadMethodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.theyukicompany.com/")]
    public partial class Contact
    {
        
        private int hIDField;
        
        private string fullNameField;
        
        private string zipCodeField;
        
        private string countryField;
        
        private string contactCodeField;
        
        private string coCNumberField;
        
        private string vATNumberField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int HID
        {
            get
            {
                return this.hIDField;
            }
            set
            {
                this.hIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string fullName
        {
            get
            {
                return this.fullNameField;
            }
            set
            {
                this.fullNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string zipCode
        {
            get
            {
                return this.zipCodeField;
            }
            set
            {
                this.zipCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string contactCode
        {
            get
            {
                return this.contactCodeField;
            }
            set
            {
                this.contactCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string CoCNumber
        {
            get
            {
                return this.coCNumberField;
            }
            set
            {
                this.coCNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string VATNumber
        {
            get
            {
                return this.vATNumberField;
            }
            set
            {
                this.vATNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.theyukicompany.com/")]
    public partial class Transaction
    {
        
        private string idField;
        
        private string hIDField;
        
        private System.DateTime transactionDateField;
        
        private string descriptionField;
        
        private decimal amountField;
        
        private string glAccountCodeField;
        
        private Contact contactField;
        
        private Document documentField;
        
        private DocumentProcessed documentProcessedField;
        
        private DocumentMatched documentMatchedField;
        
        private ForeignCurrency foreignCurrencyField;
        
        private VAT vatField;
        
        private ProjectInfo projectField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string hID
        {
            get
            {
                return this.hIDField;
            }
            set
            {
                this.hIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime transactionDate
        {
            get
            {
                return this.transactionDateField;
            }
            set
            {
                this.transactionDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string glAccountCode
        {
            get
            {
                return this.glAccountCodeField;
            }
            set
            {
                this.glAccountCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public Contact contact
        {
            get
            {
                return this.contactField;
            }
            set
            {
                this.contactField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public Document document
        {
            get
            {
                return this.documentField;
            }
            set
            {
                this.documentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public DocumentProcessed documentProcessed
        {
            get
            {
                return this.documentProcessedField;
            }
            set
            {
                this.documentProcessedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public DocumentMatched documentMatched
        {
            get
            {
                return this.documentMatchedField;
            }
            set
            {
                this.documentMatchedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public ForeignCurrency foreignCurrency
        {
            get
            {
                return this.foreignCurrencyField;
            }
            set
            {
                this.foreignCurrencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public VAT vat
        {
            get
            {
                return this.vatField;
            }
            set
            {
                this.vatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public ProjectInfo project
        {
            get
            {
                return this.projectField;
            }
            set
            {
                this.projectField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.theyukicompany.com/")]
    public partial class TransactionSearch
    {
        
        private TransactionSearchOption searchOptionField;
        
        private string searchValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public TransactionSearchOption SearchOption
        {
            get
            {
                return this.searchOptionField;
            }
            set
            {
                this.searchOptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SearchValue
        {
            get
            {
                return this.searchValueField;
            }
            set
            {
                this.searchValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.theyukicompany.com/")]
    public enum TransactionSearchOption
    {
        
        /// <remarks/>
        AmountGreaterThanEqual,
        
        /// <remarks/>
        AmountLessThanEqual,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.theyukicompany.com/")]
    public partial class OutputFields
    {
        
        private string gLAccountField;
        
        private string vATCodeField;
        
        private string paymentMethodField;
        
        private string paymentTermField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string GLAccount
        {
            get
            {
                return this.gLAccountField;
            }
            set
            {
                this.gLAccountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string VATCode
        {
            get
            {
                return this.vATCodeField;
            }
            set
            {
                this.vATCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PaymentMethod
        {
            get
            {
                return this.paymentMethodField;
            }
            set
            {
                this.paymentMethodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string PaymentTerm
        {
            get
            {
                return this.paymentTermField;
            }
            set
            {
                this.paymentTermField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.theyukicompany.com/")]
    public partial class InputFields
    {
        
        private string documentTypeField;
        
        private string contactNameField;
        
        private int priorityField;
        
        private string amountField;
        
        private string currencyField;
        
        private string startDateField;
        
        private string endDateField;
        
        private string textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DocumentType
        {
            get
            {
                return this.documentTypeField;
            }
            set
            {
                this.documentTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ContactName
        {
            get
            {
                return this.contactNameField;
            }
            set
            {
                this.contactNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Priority
        {
            get
            {
                return this.priorityField;
            }
            set
            {
                this.priorityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Currency
        {
            get
            {
                return this.currencyField;
            }
            set
            {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string StartDate
        {
            get
            {
                return this.startDateField;
            }
            set
            {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string EndDate
        {
            get
            {
                return this.endDateField;
            }
            set
            {
                this.endDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.theyukicompany.com/")]
    public partial class DefaultValue
    {
        
        private InputFields inputFieldsField;
        
        private OutputFields outputFieldsField;
        
        private System.DateTime createdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public InputFields InputFields
        {
            get
            {
                return this.inputFieldsField;
            }
            set
            {
                this.inputFieldsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public OutputFields OutputFields
        {
            get
            {
                return this.outputFieldsField;
            }
            set
            {
                this.outputFieldsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime Created
        {
            get
            {
                return this.createdField;
            }
            set
            {
                this.createdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.theyukicompany.com/")]
    public partial class ContactDefaultValues
    {
        
        private string contactIdField;
        
        private string contactNameField;
        
        private string defaultBankAccountField;
        
        private DefaultValue[] defaultValuesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ContactId
        {
            get
            {
                return this.contactIdField;
            }
            set
            {
                this.contactIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ContactName
        {
            get
            {
                return this.contactNameField;
            }
            set
            {
                this.contactNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DefaultBankAccount
        {
            get
            {
                return this.defaultBankAccountField;
            }
            set
            {
                this.defaultBankAccountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        public DefaultValue[] DefaultValues
        {
            get
            {
                return this.defaultValuesField;
            }
            set
            {
                this.defaultValuesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.theyukicompany.com/")]
    public partial class TransactionDocument
    {
        
        private string fileNameField;
        
        private byte[] filedataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string fileName
        {
            get
            {
                return this.fileNameField;
            }
            set
            {
                this.fileNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=1)]
        public byte[] filedata
        {
            get
            {
                return this.filedataField;
            }
            set
            {
                this.filedataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.theyukicompany.com/")]
    public partial class TransactionInfo
    {
        
        private string idField;
        
        private string hIDField;
        
        private System.DateTime transactionDateField;
        
        private string descriptionField;
        
        private decimal transactionAmountField;
        
        private decimal transactionAmountForeignCurrencyField;
        
        private decimal currencyRateField;
        
        private string currencyField;
        
        private string taxCodeDescriptionField;
        
        private string fullNameField;
        
        private string coCNumberField;
        
        private string vATNumberField;
        
        private int contactHIDField;
        
        private string contactCodeField;
        
        private string contactCountryField;
        
        private string contactZipcodeField;
        
        private string projectField;
        
        private string projectCodeField;
        
        private string glAccountCodeField;
        
        private string documentIDField;
        
        private string documentReferenceField;
        
        private string documentTypeField;
        
        private string documentFolderField;
        
        private string documentFolderTabField;
        
        private string contactIDField;
        
        private string periodIdField;
        
        private string companyField;
        
        private string mutationUserField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string hID
        {
            get
            {
                return this.hIDField;
            }
            set
            {
                this.hIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime transactionDate
        {
            get
            {
                return this.transactionDateField;
            }
            set
            {
                this.transactionDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal transactionAmount
        {
            get
            {
                return this.transactionAmountField;
            }
            set
            {
                this.transactionAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public decimal transactionAmountForeignCurrency
        {
            get
            {
                return this.transactionAmountForeignCurrencyField;
            }
            set
            {
                this.transactionAmountForeignCurrencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public decimal currencyRate
        {
            get
            {
                return this.currencyRateField;
            }
            set
            {
                this.currencyRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string currency
        {
            get
            {
                return this.currencyField;
            }
            set
            {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string taxCodeDescription
        {
            get
            {
                return this.taxCodeDescriptionField;
            }
            set
            {
                this.taxCodeDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string fullName
        {
            get
            {
                return this.fullNameField;
            }
            set
            {
                this.fullNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string CoCNumber
        {
            get
            {
                return this.coCNumberField;
            }
            set
            {
                this.coCNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string VATNumber
        {
            get
            {
                return this.vATNumberField;
            }
            set
            {
                this.vATNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int contactHID
        {
            get
            {
                return this.contactHIDField;
            }
            set
            {
                this.contactHIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string contactCode
        {
            get
            {
                return this.contactCodeField;
            }
            set
            {
                this.contactCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string contactCountry
        {
            get
            {
                return this.contactCountryField;
            }
            set
            {
                this.contactCountryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string contactZipcode
        {
            get
            {
                return this.contactZipcodeField;
            }
            set
            {
                this.contactZipcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string project
        {
            get
            {
                return this.projectField;
            }
            set
            {
                this.projectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string projectCode
        {
            get
            {
                return this.projectCodeField;
            }
            set
            {
                this.projectCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string glAccountCode
        {
            get
            {
                return this.glAccountCodeField;
            }
            set
            {
                this.glAccountCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string documentID
        {
            get
            {
                return this.documentIDField;
            }
            set
            {
                this.documentIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string documentReference
        {
            get
            {
                return this.documentReferenceField;
            }
            set
            {
                this.documentReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string documentType
        {
            get
            {
                return this.documentTypeField;
            }
            set
            {
                this.documentTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string documentFolder
        {
            get
            {
                return this.documentFolderField;
            }
            set
            {
                this.documentFolderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string documentFolderTab
        {
            get
            {
                return this.documentFolderTabField;
            }
            set
            {
                this.documentFolderTabField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string contactID
        {
            get
            {
                return this.contactIDField;
            }
            set
            {
                this.contactIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string periodId
        {
            get
            {
                return this.periodIdField;
            }
            set
            {
                this.periodIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string company
        {
            get
            {
                return this.companyField;
            }
            set
            {
                this.companyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string mutationUser
        {
            get
            {
                return this.mutationUserField;
            }
            set
            {
                this.mutationUserField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.theyukicompany.com/")]
    public partial class AccountStartBalance
    {
        
        private string accountIDField;
        
        private string startBalanceField;
        
        private string accountDescriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string accountID
        {
            get
            {
                return this.accountIDField;
            }
            set
            {
                this.accountIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string startBalance
        {
            get
            {
                return this.startBalanceField;
            }
            set
            {
                this.startBalanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string accountDescription
        {
            get
            {
                return this.accountDescriptionField;
            }
            set
            {
                this.accountDescriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.theyukicompany.com/")]
    public partial class AdministrationPeriod
    {
        
        private string nameField;
        
        private System.DateTime periodField;
        
        private string wholePeriodField;
        
        private bool iSO8601PeriodField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime period
        {
            get
            {
                return this.periodField;
            }
            set
            {
                this.periodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string wholePeriod
        {
            get
            {
                return this.wholePeriodField;
            }
            set
            {
                this.wholePeriodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool ISO8601Period
        {
            get
            {
                return this.iSO8601PeriodField;
            }
            set
            {
                this.iSO8601PeriodField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.theyukicompany.com/")]
    public partial class RGSEntry
    {
        
        private string yukiCodeField;
        
        private string yukiIsEnabledField;
        
        private string yukiDescriptionField;
        
        private string rgsReferenceCodeField;
        
        private string rgsDescriptionField;
        
        private string rgsFlipCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string YukiCode
        {
            get
            {
                return this.yukiCodeField;
            }
            set
            {
                this.yukiCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string YukiIsEnabled
        {
            get
            {
                return this.yukiIsEnabledField;
            }
            set
            {
                this.yukiIsEnabledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string YukiDescription
        {
            get
            {
                return this.yukiDescriptionField;
            }
            set
            {
                this.yukiDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string RgsReferenceCode
        {
            get
            {
                return this.rgsReferenceCodeField;
            }
            set
            {
                this.rgsReferenceCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string RgsDescription
        {
            get
            {
                return this.rgsDescriptionField;
            }
            set
            {
                this.rgsDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string RgsFlipCode
        {
            get
            {
                return this.rgsFlipCodeField;
            }
            set
            {
                this.rgsFlipCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.theyukicompany.com/")]
    public partial class PaymentMethod
    {
        
        private int idField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTransactions", WrapperNamespace="http://www.theyukicompany.com/", IsWrapped=true)]
    public partial class GetTransactionsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.theyukicompany.com/", Order=0)]
        public string sessionID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.theyukicompany.com/", Order=1)]
        public string administrationID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.theyukicompany.com/", Order=2)]
        public string glAccountCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.theyukicompany.com/", Order=3)]
        public System.DateTime startDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.theyukicompany.com/", Order=4)]
        public System.DateTime endDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.theyukicompany.com/", Order=5)]
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int financialMode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.theyukicompany.com/", Order=6)]
        public string dataGroups;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.theyukicompany.com/", Order=7)]
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int numberOfRecords;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.theyukicompany.com/", Order=8)]
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int startRecord;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.theyukicompany.com/", Order=9)]
        public YukiMcp.Yuki.AccountingInfo.TransactionSearch[] searchValues;
        
        public GetTransactionsRequest()
        {
        }
        
        public GetTransactionsRequest(string sessionID, string administrationID, string glAccountCode, System.DateTime startDate, System.DateTime endDate, int financialMode, string dataGroups, int numberOfRecords, int startRecord, YukiMcp.Yuki.AccountingInfo.TransactionSearch[] searchValues)
        {
            this.sessionID = sessionID;
            this.administrationID = administrationID;
            this.glAccountCode = glAccountCode;
            this.startDate = startDate;
            this.endDate = endDate;
            this.financialMode = financialMode;
            this.dataGroups = dataGroups;
            this.numberOfRecords = numberOfRecords;
            this.startRecord = startRecord;
            this.searchValues = searchValues;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTransactionsResponse", WrapperNamespace="http://www.theyukicompany.com/", IsWrapped=true)]
    public partial class GetTransactionsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.theyukicompany.com/", Order=0)]
        public YukiMcp.Yuki.AccountingInfo.Transaction[] GetTransactionsResult;
        
        public GetTransactionsResponse()
        {
        }
        
        public GetTransactionsResponse(YukiMcp.Yuki.AccountingInfo.Transaction[] GetTransactionsResult)
        {
            this.GetTransactionsResult = GetTransactionsResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.theyukicompany.com/")]
    public enum ProjectSearchOption
    {
        
        /// <remarks/>
        All,
        
        /// <remarks/>
        Company,
        
        /// <remarks/>
        Code,
        
        /// <remarks/>
        Description,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface AccountingInfoSoapChannel : YukiMcp.Yuki.AccountingInfo.AccountingInfoSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class AccountingInfoSoapClient : System.ServiceModel.ClientBase<YukiMcp.Yuki.AccountingInfo.AccountingInfoSoap>, YukiMcp.Yuki.AccountingInfo.AccountingInfoSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public AccountingInfoSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(AccountingInfoSoapClient.GetBindingForEndpoint(endpointConfiguration), AccountingInfoSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AccountingInfoSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(AccountingInfoSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AccountingInfoSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(AccountingInfoSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AccountingInfoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<YukiMcp.Yuki.AccountingInfo.GlAccount[]> GetGLAccountSchemeAsync(string sessionID, string administrationID)
        {
            return base.Channel.GetGLAccountSchemeAsync(sessionID, administrationID);
        }
        
        public System.Threading.Tasks.Task<YukiMcp.Yuki.AccountingInfo.PaymentMethod[]> GetCustomPaymentMethodsAsync(string sessionID, string administrationID)
        {
            return base.Channel.GetCustomPaymentMethodsAsync(sessionID, administrationID);
        }
        
        public System.Threading.Tasks.Task<YukiMcp.Yuki.AccountingInfo.RGSEntry[]> GetRGSSchemeAsync(string sessionID, string administrationID, string rgsVersion)
        {
            return base.Channel.GetRGSSchemeAsync(sessionID, administrationID, rgsVersion);
        }
        
        public System.Threading.Tasks.Task<YukiMcp.Yuki.AccountingInfo.AdministrationPeriod> GetPeriodDateTableAsync(string sessionID, string administrationID, int yearID)
        {
            return base.Channel.GetPeriodDateTableAsync(sessionID, administrationID, yearID);
        }
        
        public System.Threading.Tasks.Task<System.DateTime> GetFinancialYearModifiedDateAsync(string sessionID, string administrationID, int yearID)
        {
            return base.Channel.GetFinancialYearModifiedDateAsync(sessionID, administrationID, yearID);
        }
        
        public System.Threading.Tasks.Task<YukiMcp.Yuki.AccountingInfo.AccountStartBalance[]> GetStartBalanceByGlAccountAsync(string sessionID, string administrationID, int bookyear, int financialMode)
        {
            return base.Channel.GetStartBalanceByGlAccountAsync(sessionID, administrationID, bookyear, financialMode);
        }
        
        public System.Threading.Tasks.Task<YukiMcp.Yuki.AccountingInfo.TransactionInfo[]> GetTransactionDetailsAsync(string sessionID, string administrationID, string GLAccountCode, System.DateTime StartDate, System.DateTime EndDate, int financialMode)
        {
            return base.Channel.GetTransactionDetailsAsync(sessionID, administrationID, GLAccountCode, StartDate, EndDate, financialMode);
        }
        
        public System.Threading.Tasks.Task<YukiMcp.Yuki.AccountingInfo.TransactionDocument> GetTransactionDocumentAsync(string sessionID, string administrationID, string transactionID)
        {
            return base.Channel.GetTransactionDocumentAsync(sessionID, administrationID, transactionID);
        }
        
        public System.Threading.Tasks.Task<YukiMcp.Yuki.AccountingInfo.ContactDefaultValues[]> GetContactDefaultValuesAsync(string sessionID, string administrationID, string contactID)
        {
            return base.Channel.GetContactDefaultValuesAsync(sessionID, administrationID, contactID);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YukiMcp.Yuki.AccountingInfo.GetTransactionsResponse> YukiMcp.Yuki.AccountingInfo.AccountingInfoSoap.GetTransactionsAsync(YukiMcp.Yuki.AccountingInfo.GetTransactionsRequest request)
        {
            return base.Channel.GetTransactionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<YukiMcp.Yuki.AccountingInfo.GetTransactionsResponse> GetTransactionsAsync(string sessionID, string administrationID, string glAccountCode, System.DateTime startDate, System.DateTime endDate, int financialMode, string dataGroups, int numberOfRecords, int startRecord, YukiMcp.Yuki.AccountingInfo.TransactionSearch[] searchValues)
        {
            YukiMcp.Yuki.AccountingInfo.GetTransactionsRequest inValue = new YukiMcp.Yuki.AccountingInfo.GetTransactionsRequest();
            inValue.sessionID = sessionID;
            inValue.administrationID = administrationID;
            inValue.glAccountCode = glAccountCode;
            inValue.startDate = startDate;
            inValue.endDate = endDate;
            inValue.financialMode = financialMode;
            inValue.dataGroups = dataGroups;
            inValue.numberOfRecords = numberOfRecords;
            inValue.startRecord = startRecord;
            inValue.searchValues = searchValues;
            return ((YukiMcp.Yuki.AccountingInfo.AccountingInfoSoap)(this)).GetTransactionsAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<YukiMcp.Yuki.AccountingInfo.ProjectBalance[]> GetProjectBalanceAsync(string sessionID, string administrationID, string GLAccountCode, string projectCode, System.DateTime StartDate, System.DateTime EndDate)
        {
            return base.Channel.GetProjectBalanceAsync(sessionID, administrationID, GLAccountCode, projectCode, StartDate, EndDate);
        }
        
        public System.Threading.Tasks.Task<YukiMcp.Yuki.AccountingInfo.Project[]> GetProjectsAsync(string sessionID, string administrationID, YukiMcp.Yuki.AccountingInfo.ProjectSearchOption searchOption, string searchValue)
        {
            return base.Channel.GetProjectsAsync(sessionID, administrationID, searchOption, searchValue);
        }
        
        public System.Threading.Tasks.Task<YukiMcp.Yuki.AccountingInfo.Project[]> GetProjectsAndIDAsync(string sessionID, string administrationID, YukiMcp.Yuki.AccountingInfo.ProjectSearchOption searchOption, string searchValue)
        {
            return base.Channel.GetProjectsAndIDAsync(sessionID, administrationID, searchOption, searchValue);
        }
        
        public System.Threading.Tasks.Task<string> AuthenticateAsync(string accessKey)
        {
            return base.Channel.AuthenticateAsync(accessKey);
        }
        
        public System.Threading.Tasks.Task<string> AuthenticateClientAsync(string clientID, string clientSecret, string accessKey)
        {
            return base.Channel.AuthenticateClientAsync(clientID, clientSecret, accessKey);
        }
        
        public System.Threading.Tasks.Task<string> AuthenticateByUserNameAsync(string userName, string password)
        {
            return base.Channel.AuthenticateByUserNameAsync(userName, password);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> DomainsAsync(string sessionID)
        {
            return base.Channel.DomainsAsync(sessionID);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> CompaniesAsync(string sessionID)
        {
            return base.Channel.CompaniesAsync(sessionID);
        }
        
        public System.Threading.Tasks.Task<string> AdministrationIDAsync(string sessionID, string administrationName)
        {
            return base.Channel.AdministrationIDAsync(sessionID, administrationName);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> AdministrationsAsync(string sessionID)
        {
            return base.Channel.AdministrationsAsync(sessionID);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> AdministrationsWithInternalCustomerCodeAsync(string sessionID)
        {
            return base.Channel.AdministrationsWithInternalCustomerCodeAsync(sessionID);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetCurrentDomainAsync(string sessionID)
        {
            return base.Channel.GetCurrentDomainAsync(sessionID);
        }
        
        public System.Threading.Tasks.Task SetCurrentDomainAsync(string sessionID, string domainID)
        {
            return base.Channel.SetCurrentDomainAsync(sessionID, domainID);
        }
        
        public System.Threading.Tasks.Task<string> LanguageAsync(string sessionID)
        {
            return base.Channel.LanguageAsync(sessionID);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> SupportedLanguagesAsync(string sessionID)
        {
            return base.Channel.SupportedLanguagesAsync(sessionID);
        }
        
        public System.Threading.Tasks.Task SetLanguageAsync(string sessionID, string language)
        {
            return base.Channel.SetLanguageAsync(sessionID, language);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AccountingInfoSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.AccountingInfoSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AccountingInfoSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://api.yukiworks.be/ws/AccountingInfo.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.AccountingInfoSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://api.yukiworks.be/ws/AccountingInfo.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            AccountingInfoSoap,
            
            AccountingInfoSoap12,
        }
    }
}
